SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
/*------ 
VER. ZCCU_2026.01.14
*/ 
CREATE PROCEDURE [dbo].[psControlSTP] (@Fecha SMALLDATETIME)  
AS 

BEGIN  

	EXEC [10.0.2.14].[FINMAS].[DBO].[psControlSTP] @Fecha---'20260113'
END;
GO