SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE  [dbo].[pXaCaFNCartaPromotor3APP] @CODASESOR VARCHAR(30)
AS
SET NOCOUNT ON        

DECLARE @FECHA SMALLDATETIME
SELECT @FECHA=FECHACONSOLIDACION FROM VCSFECHACONSOLIDACION WITH(NOLOCK)

--DECLARE @CODASESOR VARCHAR(30)
--SET @CODASESOR='KCH820616FH800'

SELECT FECHACONSULTA,SUCURSAL,PROMOTOR,ANTIGUEDAD,NIVEL_PROMOTOR,BONO_ESTIMADO_CALCULADO,CA_VTGE0A30_INI,	
CA_VTGE0A30_FIN,PTMOS_VGTE_INI,PTMOS_VGTE_FIN,MONTO_ASIG,PTMOS_ASIG,MONTO_QUITAS,PTMOS_QUITAS,DIFF_CARTERA,	
SALDO_CRECIMIENTO_META,CUMP_CARTERA,CRECI_PTMOS_VGTES,PTMOS_CRECIMIENTO_META,CUMP_CLIENTES,PROGRAMADO_S,	
MONTO_COBRADO,PAGO_PUNTUAL,PAGO_ACUMULADO,CART_VENCIDA_INI,CART_VENCIDA_FIN,SALDO_RIESGO,PTMOS_RIESGO,	
MOTO_COLOCACION_TOTAL,PTMOS_COLOCACION_TOTAL,	MONTO_NUEVOS,PTMOS_NUEVOS,MONTO_RENOV,PTMOS_RENOV,	
MONTO_REACTIVACIONES,PTMOS_REACTIVACIONES,SALDO_VGTE_INI_C1,SALDO_VGTE_FIN_C1,DIF_SALDO_C1,	
PTMOS_VGTE_INI_C1,PTMOS_VGTE_FIN_C1,DIF_PTMOS_C1,SALDO_VGTE_INI_C2,SALDO_VGTE_FIN_C2,DIF_SALDO_C2,	
PTMOS_VGTE_INI_C2,PTMOS_VGTE_FIN_C2,DIF_PTMOS_C2,SALDO_VGTE_INI_C3,SALDO_VGTE_FIN_C3,DIF_SALDO_C3,	
PTMOS_VGTE_INI_C3,PTMOS_VGTE_FIN_C3,DIF_PTMOS_C3,SALDO_VGTE_INI_C4a10,SALDO_VGTE_FIN_C4a10,DIF_SALDO_C4a10,	
PTMOS_VGTE_INI_C4a10,PTMOS_VGTE_FIN_C4a10,	DIF_PTMOS_C4a10,SALDO_VGTE_INI_C11,SALDO_VGTE_FIN_C11,DIF_SALDO_C11M,	
PTMOS_VGTE_INI_C11,PTMOS_VGTE_FIN_C11,DIF_PTMOS_C11M,PORCE_PASO_VENCIDA,PORCE_PENALIZACION,PORCE_BONO_CRECIMIENTO,	
PORCE_BONO_COBRANZA,PORCE_BONO_GANADO,SALDO_BONO_GANADO,
--->Nuevos Campos
DIFF_CARTERA_VENCIDA,MONTO_RENOV_ANT,PTMOS_RENOV_ANT,IMOR7,IMOR15,IMOR30,PORCE_BONO_IMOR  
FROM FNMGCONSOLIDADO.DBO.TCACARTAPROMOTOR3APP WITH(NOLOCK)
WHERE FECHACONSULTA=@FECHA AND CODASESOR=@CODASESOR
GO