SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
/****** Seguimiento Pagos Semanales 

Solicitado por Mauricio 2024.12.20
--Siempre se mostraría la información al corte del día anterior
--A cada promotor le debe de aparecer únicamente su información
--Seria un listado, incluyendo los campos: 
NombreCompleto Nombre, 
DIA_DE_PAGO Dia Pago, 
PagoRequeridoDinamico_Segui Pago Requerido, 
PagoActual_Segui Pago Actual, 
EstatusActual_Segui Estatus Actual

--Y poder incluir dos filtros, uno por DIA_DE_PAGO Dia Pago, y EstatusActual_Segui Estatus

*****/
CREATE PROCEDURE [dbo].[pXaCASeguiPagosPromotor] @CODASESOR VARCHAR(15),@DiaPagoPro INT,@EstatusPro INT   
as  
set nocount on  

---------------------pruebas
--DECLARE @CODASESOR VARCHAR(20)
--SELECT @CODASESOR='MPY821221FM200'

--DECLARE @DÍA INT
--SELECT @DÍA=0

--DECLARE @ESTATUS INT
--SELECT @ESTATUS = 0
------------------------------------
DECLARE @DÍA INT
SELECT @DÍA= @DiaPagoPro

DECLARE @ESTATUS INT
SELECT @ESTATUS = @EstatusPro

DECLARE @FECHA SMALLDATETIME
SELECT @FECHA=FECHACONSOLIDACION FROM VCSFECHACONSOLIDACION

/*  FILTROS POR DIA DE PAGO
0 - TODOS
1 - LUNES
2 - MARTES
3 - MIERCOLES
4 - JUEVES
5 - VIERNES

*/

/*  FILTROS POR ESTATUSACTUAL
0 - TODOS
1 - PAGO PARCIAL
2 - PENDIENTE
3 - PAGADO
*/


DECLARE @DÍAPAGO INT
DECLARE @ESTATUSPAGO INT

SELECT @DÍAPAGO = CASE  WHEN @DÍA = 1 THEN 1--'LUNES' 
					    WHEN @DÍA = 2 THEN 2--'MARTES' 
					    WHEN @DÍA = 3 THEN 3--'MIERCOLES' 
					    WHEN @DÍA = 4 THEN 4--'JUEVES' 
					    WHEN @DÍA = 5 THEN 5--'VIERNES' 
					    WHEN @DÍA = 0 THEN 0-- TODOS
					    END

SELECT @ESTATUSPAGO = CASE  WHEN @ESTATUS = 1 THEN 1--'PAGO PARCIAL' 
						    WHEN @ESTATUS = 2 THEN 2--'PENDIENTE' 
						    WHEN @ESTATUS = 3 THEN 3--'PAGADO'  
						    WHEN @ESTATUS = 0 THEN 0-- TODOS
						    END
--SELECT @DÍAPAGO,@ESTATUS


--30,589
SELECT S.[NOMBRECOMPLETO] NOMBRECLIENTE,S.[DIA_DE_PAGO] DIAPAGO,S.[PAGOREQUERIDODINAMICO_SEGUI]PAGOREQUERIDO
,S.[PAGOACTUAL_SEGUI]PAGOACTUAL,S.[ESTATUSACTUAL_SEGUI] ESTATUSACTUAL,E.CodUsuario CODASESOR ,S.[CODPRESTAMO]
,CASE WHEN [DIA_DE_PAGO]= 'LUNES'      THEN 1 
	 WHEN [DIA_DE_PAGO] = 'MARTES'     THEN 2
	 WHEN [DIA_DE_PAGO] = 'MIERCOLES'  THEN 3
	 WHEN [DIA_DE_PAGO] = 'JUEVES'     THEN 4
	 WHEN [DIA_DE_PAGO] = 'VIERNES'    THEN 5 
	 END DIAPAGOFILTRO
,0 DIAPAGOTODOS
,CASE WHEN [ESTATUSACTUAL_SEGUI]= 'PAGO PARCIAL' THEN 1 
	 WHEN [ESTATUSACTUAL_SEGUI] = 'PENDIENTE'    THEN 2
	 WHEN [ESTATUSACTUAL_SEGUI] = 'PAGADO'       THEN 3
	 END PAGOACTUALFILTRO
,0 PAGOACTUALTODOS
INTO #BASEPROMO
FROM [FNMGCONSOLIDADO].[DBO].[TCASEGUIPAGOSPROMOTOR] S WITH(NOLOCK)
--LEFT OUTER JOIN TCSCARTERA CA WITH(NOLOCK) ON CA.CODPRESTAMO=S.CODPRESTAMO AND CA.FECHA=S.FECHACONSULTA_INI
--LEFT OUTER JOIN TCSEMPLEADOSFECHA E WITH(NOLOCK) ON E.CODUSUARIO=CA.CODASESOR AND E.CODPUESTO=66 AND E.FECHA=S.FECHACONSULTA_INI
INNER JOIN tCsEmpleados E WITH(NOLOCK) ON (E.Paterno+ ' '+E.Materno+' '+E.Nombres)= S.Promotor
WHERE FECHAACTUALIZA = @FECHA
AND PROMOTOR NOT IN ('HUERFANO')
AND E.CODUSUARIO = @CODASESOR
	 
SELECT  NombreCliente,DiaPago,PagoRequerido,PagoActual,EstatusActual
FROM #BasePromo	 WITH(NOLOCK)
WHERE (CASE WHEN @DÍAPAGO = 0 THEN DIAPAGOTODOS ELSE  DIAPAGOFILTRO END ) IN ( @DÍAPAGO )
AND (CASE WHEN @ESTATUSPAGO = 0 THEN PAGOACTUALTODOS  ELSE  PAGOACTUALFILTRO END ) IN ( @ESTATUSPAGO )
	 
DROP TABLE #BASEPROMO
GO