SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
/*------ 
VER. ZCCU_2026.01.19
*/ 
CREATE PROCEDURE [dbo].[psControlCirculo] (@Fecha SMALLDATETIME)  
AS 

BEGIN  

	EXEC [10.0.2.14].[FINMAS].[DBO].[psControlCirculo] @Fecha---'20260113'--
END;
GO