SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
/*------ 
VER. ZCCU_2026.01.27
*/ 
CREATE PROCEDURE [dbo].[psControlAltasEmpleados] (@Fecha SMALLDATETIME)  
AS 

BEGIN  

--DECLARE @FECHA SMALLDATETIME
--SELECT @FECHA = FECHACONSOLIDACION FROM VCSFECHACONSOLIDACION WITH(NOLOCK)          
         
DECLARE @FECINI SMALLDATETIME         
SET @FECINI = '20260101'--DBO.FDUFECHAAPERIODO(@FECHA)+'01'         

SELECT CASE WHEN ISNULL(CODUSUARIO,'0')='0' THEN Paterno +' '+Materno+' '+Nombres 
	WHEN ISNULL(CODUSUARIO,'0')='' THEN Paterno +' '+Materno+' '+Nombres ELSE '' END nombreCompleto
,CASE WHEN ISNULL(CODUSUARIO,'0')='0' THEN 'red' WHEN ISNULL(CODUSUARIO,'0')='' THEN 'orange' ELSE '#AFECAA' END Color
,CASE WHEN ISNULL(CODUSUARIO,'0')='0' THEN 0 WHEN ISNULL(CODUSUARIO,'0')='' THEN 0 ELSE 1 END valor
,CASE WHEN ISNULL(CODUSUARIO,'0')='0' THEN 'Sin Generar' WHEN ISNULL(CODUSUARIO,'0')='' THEN 'Sin Generar' ELSE 'Generado' END Detalle
--SELECT *
FROM tCsEmpleados WITH(NOLOCK)
WHERE Ingreso >= @FECINI

END;
GO