SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

/*
ZCCU 2024.09.10 
SP PARA GENERAR LOS USUARIOS QUE HAN SIDO DESHABILITADOS DE LAS BAJAS DEL MES
 */

CREATE PROCEDURE [dbo].[pCsUsuariosDeshabilitados] 
AS
SET NOCOUNT ON    

DECLARE @FECHA SMALLDATETIME  
SELECT @FECHA=FECHACONSOLIDACION FROM VCSFECHACONSOLIDACION           
--SET @FECHA='20240831'        
       
DECLARE @FECHAINI  SMALLDATETIME        
SET @FECHAINI = dbo.fdufechaaperiodo(@fecha)+'01'      
      
        
SELECT 
--e.codusuario,
O.NOMOFICINA SUCURSAL,INGRESO,SALIDA,PATERNO,MATERNO,NOMBRES,P.DESCRIPCION PUESTO,-----E.CODPUESTO, 
case when e.CodMBaja = '5' then 'Defuncion'
when E.codmbaja in ('1','3') then 'Renuncia' else  'Despido' end as  'TIPO DE SALIDA'  
,us.USUARIO, CASE WHEN US.activo=0 THEN 'USUARIO DESHABILITADO' ELSE 'USUARIO ACTIVO' END ESTATUS   
FROM TCSEMPLEADOS E WITH(NOLOCK)        
INNER JOIN TCSCLPUESTOS P WITH(NOLOCK) ON P.CODIGO=E.CODPUESTO        
INNER JOIN TCLOFICINAS O WITH(NOLOCK) ON O.CODOFICINA=E.CODOFICINANOM    
inner join tsgusuarios us    WITH(NOLOCK) ON us.codusuario=e.codusuario and  activo=0 and not  us.codusuario='' 
WHERE E.ESTADO=0 AND SALIDA>=@FECHAINI AND SALIDA<=@FECHA     
and  not e.codusuario=''    
ORDER BY SALIDA DESC   
GO