SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[pCsAlertaOperacionesDia217] 
AS 
SET NOCOUNT ON 
BEGIN
-- ES 1 PARA REPORTES: MUESTRA EL RESULTADO DEL LOG (Cuando haya alertas) 
-- ES 0 PARA PONERLO EN UN WORKER Y NO DEVUELVA INFORMACION EN PANTALLA.

EXEC [10.0.2.14].[FINMAS].[DBO].[pCsAlertaOperacionesDia] 1

END;
GO