SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
---SP para generar informacion para el reporte Operativo enviado a DG      
--se optimiza sp 2023.10.16 zccu  


-------- TABLA 4  
CREATE PROCEDURE [dbo].[pCsROCreCAVigte]  
AS  
SET NOCOUNT ON  

  
/* GRAFICA1.CRECIMIENTO DE CARTERA VIGENTE EN EL MES*/    
DECLARE @FECHA SMALLDATETIME    
SET @FECHA=(SELECT FECHACONSOLIDACION FROM VCSFECHACONSOLIDACION)    
     
DECLARE @FECINI SMALLDATETIME    
SET @FECINI = CAST(DBO.FDUFECHAAPERIODO(@FECHA)+'01' AS SMALLDATETIME)-1      
    
SELECT C.FECHA FECHA,C.CODPRESTAMO  CODPRESTAMO   
INTO #CA  
FROM TCSCARTERA C WITH(NOLOCK)    
WHERE C.FECHA>=@FECINI AND C.FECHA<=@FECHA  
AND C.CODOFICINA NOT IN('97','231','230','999')   
AND C.ESTADO='VIGENTE'    
GROUP BY  C.FECHA ,C.CODPRESTAMO   
ORDER BY C.FECHA    
  
SELECT T.FECHA FECHA,T.CODPRESTAMO CODPRESTAMO,SUM(T.SALDOCAPITAL)SALDOCAPITAL    
INTO #CAD  
FROM TCSCARTERADET T WITH(NOLOCK)    
WHERE FECHA>=@FECINI AND FECHA<=@FECHA  
AND CODPRESTAMO IN (SELECT CODPRESTAMO FROM #CA WITH(NOLOCK) GROUP BY CODPRESTAMO)  
GROUP BY FECHA,CODPRESTAMO   
ORDER BY FECHA 
   
-------VALIDAR --- TABLA TEMPORAL / SE BORRA TODA E SE INSERTAN NUEVOS REGISTROS.-- ZCCU  
DELETE FROM FNMGCONSOLIDADO.DBO.TmpROCreCAVigte   
INSERT INTO FNMGCONSOLIDADO.DBO.TmpROCreCAVigte  

SELECT C.FECHA,SUM(T.SALDOCAPITAL)SALDOTOTAL    
--INTO FNMGCONSOLIDADO.DBO.tmpROCreCAVigte  
FROM #CA C WITH(NOLOCK)    
INNER JOIN #CAD T WITH(NOLOCK) ON C.FECHA=T.FECHA AND C.CODPRESTAMO=T.CODPRESTAMO    
GROUP BY  C.FECHA  
  
DROP TABLE #CA  
DROP TABLE #CAD  
  
  
---SELECT * FROM FNMGCONSOLIDADO.DBO.tmpROCreCAVigte  
  
  
  
GO