SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
----select dbo.fduCalculoCURP2017('MARIA OLGA','EK','','19661104')--,len(dbo.fduCalculoRFC2017('JOSE','UCH','CUPUL','19780704')) largo
----select dbo.fduCalculoCURP2017('CHRISTOFER ROGGER','URBIZAGASTEGUI','MONTOYA','19790918')--UIMC790918HNERNH04
----drop function fduCalculoCURP2017
CREATE function [dbo].[fduCalculoCURP2017_10] ( --> 2.17
--alter function [dbo].[fduCalculoCURP2017] (
    @NOMBRES_AUX VARCHAR(100),
    @APATERNO_AUX VARCHAR(100),
    @AMATERNO_AUX VARCHAR(100),
    @FECHANACIMIENTO SmallDateTime--,
	--@genero bit,
	--@estado varchar(10)
)    
returns varchar(30)
--with encryption
AS
begin
--declare @NOMBRES_AUX VARCHAR(100)
--declare @APATERNO_AUX VARCHAR(100)
--declare @AMATERNO_AUX VARCHAR(100)
--declare @FECHANACIMIENTO SmallDateTime
--declare @genero bit
--declare @estado varchar(10)

--set @NOMBRES_AUX ='MA CECILIA'--'MARIA OLGA'
--set @APATERNO_AUX ='MUÑOZ'--'EK'
--set @AMATERNO_AUX ='AMARO'--''
--set @FECHANACIMIENTO='19691122'--'19661104'
--set @genero=0
--set @estado='000029'

--DECLARACION DE VARIABLES
declare @RFC_OUT varchar(30)
DECLARE @NOMBRES VARCHAR(100)
DECLARE @APATERNO VARCHAR(100)
DECLARE @AMATERNO VARCHAR(100)
DECLARE @T_NOMTOT CHAR(52)
DECLARE @NOMBRE1 VARCHAR(100) --PRIMER NOMBRE
DECLARE @NOMBRE2 VARCHAR(100) --DEMAS NOMBRES
DECLARE @NOMBRES_LONGITUD INT --LONGITUD DE TODOS @NOMBRES
DECLARE @NOMBRE1_LONGITUD INT --LONGITUD DEL PRIMER NOMBRE(MAS UNO,EL QUE SOBRA ES UN ESPACIO EN BLANCO)
DECLARE @APATERNO1 VARCHAR(100) --PRIMER NOMBRE
DECLARE @APATERNO2 VARCHAR(100) --DEMAS NOMBRES
DECLARE @APATERNO_LONGITUD INT --LONGITUD DE TODOS @NOMBRES
DECLARE @APATERNO1_LONGITUD INT --LONGITUD DEL PRIMER NOMBRE(MAS UNO,EL QUE SOBRA ES UN ESPACIO EN BLANCO)
DECLARE @AMATERNO1 VARCHAR(100) --PRIMER NOMBRE
DECLARE @AMATERNO2 VARCHAR(100) --DEMAS NOMBRES
DECLARE @AMATERNO_LONGITUD INT --LONGITUD DE TODOS @NOMBRES
DECLARE @AMATERNO1_LONGITUD INT --LONGITUD DEL PRIMER NOMBRE(MAS UNO,EL QUE SOBRA ES UN ESPACIO EN BLANCO)
DECLARE @VARLOOPS INT --VARIABLE PARA LOS LOOPS, SE INICIALIZA AL INICIR UN LOOP
DECLARE @RFC CHAR(16)
DECLARE @T_NOMNUM CHAR(102) --Nombre numerico
DECLARE @T_SUMA INT
DECLARE @T_DIVID INT -- Dividendo
DECLARE @T_MOD INT -- MOD de la division
DECLARE @T_HOMOCLV CHAR(3) -- Homoclave
DECLARE @T_NUMERO INT -- Numero ASC asignado a un caracter
DECLARE @T_PARCIAL INT -- Acumulado de la suma de los caracteres del RFC

if (substring(@APATERNO_AUX,1,1) in('Ñ','ñ')) set @APATERNO_AUX= 'X'+substring(@APATERNO_AUX,2,len(@APATERNO_AUX))
if (substring(@AMATERNO_AUX,1,1) in('Ñ','ñ')) set @AMATERNO_AUX= 'X'+substring(@AMATERNO_AUX,2,len(@AMATERNO_AUX))
if (substring(@NOMBRES_AUX,1,1) in('Ñ','ñ')) set @NOMBRES_AUX= 'X'+substring(@NOMBRES_AUX,2,len(@NOMBRES_AUX))

--INICIALZA VARIABLES
SET @NOMBRES = LTRIM(RTRIM(@NOMBRES_AUX))
SET @APATERNO = LTRIM(RTRIM(@APATERNO_AUX))
SET @AMATERNO = LTRIM(RTRIM(@AMATERNO_AUX))
SET @T_NOMTOT =@APATERNO+' '+@AMATERNO+' '+@NOMBRES

--Print @NOMBRES 
--Print @APATERNO 
--Print @AMATERNO 
--Print @T_NOMTOT 
--PROCESAR NOMBRES DE PILA
SET @VARLOOPS = 0
WHILE @VARLOOPS <> 1
BEGIN
    SET @NOMBRES_LONGITUD = LEN(@NOMBRES)
    SET @NOMBRE1_LONGITUD = PATINDEX('% %',@NOMBRES)
    IF @NOMBRE1_LONGITUD = 0
        SET @NOMBRE1_LONGITUD = @NOMBRES_LONGITUD
    SET @NOMBRE1 = RTRIM(LEFT(@NOMBRES,@NOMBRE1_LONGITUD))
    SET @NOMBRE2 = LTRIM(RIGHT(@NOMBRES,@NOMBRES_LONGITUD - @NOMBRE1_LONGITUD))

    --SE QUITAN LOS NOMBRES DE JOSE, MARIA,MA,MA.
    IF @NOMBRE1 IN ('JOSE','MARIA','MA.','DE','LA','LAS','MC','VON','DEL','LOS','Y','MAC','VAN','J','M','MA') AND @NOMBRE2 <> ''
    BEGIN
        SET @NOMBRES = @NOMBRE2
    END 
    ELSE
    BEGIN
        SET @VARLOOPS = 1
    END
END

--PROCESAMOS APELLIDOS, PATERNO EN UN LOOP
SET @VARLOOPS = 0
WHILE @VARLOOPS <> 1
BEGIN	
	--PRINT 'PATERNO PROCESO: '+ isnull(@APATERNO1, 'NULO')
	SET @APATERNO_LONGITUD = LEN(@APATERNO)
	SET @APATERNO1_LONGITUD = PATINDEX('% %',@APATERNO)

	IF @APATERNO1_LONGITUD = 0
	    SET @APATERNO1_LONGITUD = @APATERNO_LONGITUD
	
	SET @APATERNO1 = RTRIM(LEFT(@APATERNO,@APATERNO1_LONGITUD))
	SET @APATERNO2 = LTRIM(RIGHT(@APATERNO,@APATERNO_LONGITUD - @APATERNO1_LONGITUD))
	
	--SE QUINTAN LOS SUFIJOS
	IF @APATERNO1 IN ('DE','LA','LAS','MC','VON','DEL','LOS','Y','MAC','VAN') AND @APATERNO2 <> ''
	BEGIN
		SET @APATERNO = @APATERNO2
	END 
	ELSE
    BEGIN
	    SET @APATERNO1 	= @APATERNO1 + ' ' + @APATERNO2
	    SET @VARLOOPS 	= 1
    END
END

--PROCESAMOS APELLIDOS, MATERNO EN UN LOOP
SET @VARLOOPS = 0
WHILE @VARLOOPS <> 1
BEGIN
    SET @AMATERNO_LONGITUD = LEN(@AMATERNO)
    SET @AMATERNO1_LONGITUD = PATINDEX('% %',@AMATERNO)

    IF @AMATERNO1_LONGITUD = 0
        SET @AMATERNO1_LONGITUD = @AMATERNO_LONGITUD

    SET @AMATERNO1 = RTRIM(LEFT(@AMATERNO,@AMATERNO1_LONGITUD))
    SET @AMATERNO2 = LTRIM(RIGHT(@AMATERNO,@AMATERNO_LONGITUD - @AMATERNO1_LONGITUD))

    --SE QUITAN LOS SUFIJOS
    IF @AMATERNO1 IN ('DE','LA','LAS','MC','VON','DEL','LOS','Y','MAC','VAN') AND @AMATERNO2 <> ''
    BEGIN
        SET @AMATERNO = @AMATERNO2
    END 
    ELSE
    BEGIN
        SET @VARLOOPS = 1
    END
END
--PRINT 'PATERNO FINAL: '+ @APATERNO1
--PRINT 'MATERNO FINAL: '+ @AMATERNO1
--PRINT 'NOMBRE FINAL: '+@NOMBRE1
if (@APATERNO1<>'' and @AMATERNO1<>'')
begin
	--print 'aqui <> '
	--if (len(@APATERNO1)>2)-- CUANDO LOS APELLIDO PATERNO ES MAYOR A 2 CARACTERES
	--	begin
			--print 'aqui >2 '
			--SE OBTIENE DEL PRIMER APELLIDO LA PRIMER LETRA Y LA PRIMER VOCAL INTERNA
			SET @RFC = LEFT(@APATERNO1,1)
			SET @APATERNO1_LONGITUD= LEN(@APATERNO1)
			SET @VARLOOPS = 1 --EMPIEZA EN UNO POR LA PRIMERA LETRA SE LA VA A SALTAR

			WHILE @APATERNO1_LONGITUD > @VARLOOPS
			BEGIN
				SET @VARLOOPS = @VARLOOPS + 1
				IF SUBSTRING(@APATERNO1,@VARLOOPS,1) IN ('A','E','I','O','U','/','-','.','´')
				BEGIN
					SET @RFC = RTRIM(@RFC)+CONVERT(CHAR(1),SUBSTRING(@APATERNO1,@VARLOOPS,1))
					SET @VARLOOPS = @APATERNO1_LONGITUD
				END
			END	
			--print '@RFC:' + isnull(@RFC,'')
			if (len(@RFC)=1) --EN LOS CASOS QUE EL APELLIDO PATERNO NO FIGURE NINGUNA VOCAL DESPUES DE LA PRIMERA LETRA SE COLOCARA UNA X
				begin
					SET @RFC = RTRIM(@RFC)+'X'--CONVERT(CHAR(2),SUBSTRING(@APATERNO1,1,2))
				end
			--print '@RFC2:' + isnull(@RFC,'')
			--SE OBTIENE LA PRIMER LETRA DEL APELLIDO MATERNO
			SET @RFC = RTRIM(@RFC)+CONVERT(CHAR(1),SUBSTRING(@AMATERNO1,1,1))
			--SE LE AGREGA LA PRIMER LETRA DEL NOMBRE
			SET @RFC = RTRIM(@RFC)+CONVERT(CHAR(1),SUBSTRING(@NOMBRE1,1,1))
		--end
	--else
	--	begin
	--		--print 'aqui <2 '
	--		--print '@RFC: ' + isnull(@RFC,'')
	--		SET @RFC = LEFT(@APATERNO1,1)
	--		--print '@RFC1: ' + @RFC
	--		SET @RFC = RTRIM(@RFC)+CONVERT(CHAR(1),SUBSTRING(@AMATERNO1,1,1))
	--		--print '@RFC2: ' + @RFC
	--		SET @RFC = RTRIM(@RFC)+CONVERT(CHAR(2),SUBSTRING(@NOMBRE1,1,2))
	--		--print '@RFC3: ' + @RFC
	--	end
end
else
	begin
		if(@APATERNO1<>'')
		begin
			if (len(@APATERNO1)>2)-- CUANDO LOS APELLIDO PATERNO ES MAYOR A 2 CARACTERES
				begin
					--SE OBTIENE DEL PRIMER APELLIDO LA PRIMER LETRA Y LA PRIMER VOCAL INTERNA
					SET @RFC = LEFT(@APATERNO1,1)
					SET @APATERNO1_LONGITUD= LEN(@APATERNO1)
					SET @VARLOOPS = 1 --EMPIEZA EN UNO POR LA PRIMERA LETRA SE LA VA A SALTAR
					WHILE @APATERNO1_LONGITUD > @VARLOOPS
					BEGIN
						SET @VARLOOPS = @VARLOOPS + 1
						IF SUBSTRING(@APATERNO1,@VARLOOPS,1) IN ('A','E','I','O','U','/','-','.','´')
						BEGIN
							SET @RFC = RTRIM(@RFC)+CONVERT(CHAR(1),SUBSTRING(@APATERNO1,@VARLOOPS,1))
							SET @VARLOOPS = @APATERNO1_LONGITUD
						END
					END
				end
			else
				begin
					SET @RFC = LEFT(@APATERNO1,2)
				end
		end
		if(@AMATERNO1<>'')
		begin
			if(len(@AMATERNO1)>2)
				begin
					--SE OBTIENE DEL PRIMER APELLIDO LA PRIMER LETRA Y LA PRIMER VOCAL INTERNA
					SET @RFC = LEFT(@AMATERNO1,1)
					SET @AMATERNO1_LONGITUD= LEN(@AMATERNO1)
					SET @VARLOOPS = 1 --EMPIEZA EN UNO POR LA PRIMERA LETRA SE LA VA A SALTAR
					WHILE @AMATERNO1_LONGITUD > @VARLOOPS
					BEGIN
						SET @VARLOOPS = @VARLOOPS + 1
						IF SUBSTRING(@AMATERNO1,@VARLOOPS,1) IN ('A','E','I','O','U','/','-','.','´')
						BEGIN
							SET @RFC = RTRIM(@RFC)+CONVERT(CHAR(1),SUBSTRING(@AMATERNO1,@VARLOOPS,1))
							SET @VARLOOPS = @AMATERNO1_LONGITUD
						END
					END
				end
			else
				begin
					--print 'aqui <2 '
					--print '@RFC1: ' + isnull(@RFC,'')
					SET @RFC = LEFT(@AMATERNO1,2)
				end
		end
		--SE LE AGREGA UNA 'X' POR EL APELLIDO FALTANTE
		SET @RFC = RTRIM(@RFC)+'X'
		--SE LE AGREGA LA PRIMERA LETRA DEL NOMBRE
		SET @RFC = RTRIM(@RFC)+CONVERT(CHAR(1),SUBSTRING(@NOMBRE1,1,1))
	end
--select @RFC
--SE LE AGREGA LA FECHA DE NACIMIENTO
SET @RFC = RTRIM(@RFC) + CONVERT(CHAR,@FECHANACIMIENTO,12)

SET @RFC_OUT = @RFC
IF substring(@RFC_OUT,1, 4) in ('BACA','BAKA','BUEI','BUEY','CACA','CACO','CAGA','CAGO','CAKA','CAKO','COGE','COGI','COJA','COJE','COJI','COJO','CULO','FALO','FETO'
,'GETA','GUEI','GUEY','JETA','JOTO','KACA','KACO','KAGA','KAGO','KAKA','KAKO','KOGE','KOGI','KOJA','KOJE','KOJI','KOJO','KOLA','KULO','LILO'
,'LOCA','LOCO','LOKA','LOKO','MAME','MAMO','MEAR','MEAS','MEON','MIAR','MION','MOCO','MOKO','MULA','MULO','NACA','NACO','PEDA','PEDO','PENE'
,'PIPI','PITO','POPO','PUTA','PUTO','QULO','RATA','ROBA','ROBE','ROBO','RUIN','SENO','TETA','VACA','VAGA','VAGO','VAKA','VUEI','VUEY','WUEI','WUEY'
)
BEGIN
	Set @RFC_OUT = substring(@RFC_OUT,1, 1) + 'X' + substring(@RFC_OUT,3, 50)
END

--if(@genero=1)
--	begin
--		set @RFC_OUT=LTRIM(RTRIM(@RFC_OUT))+'H'
--	end
--	else
--	begin
--		set @RFC_OUT=LTRIM(RTRIM(@RFC_OUT))+'M'
--	end

--declare @ef char(2)
--SELECT @ef=campo3 FROM tClUbiGeo WHERE CodUbigeoTipo = 'ESTA' and CodUbigeo=@estado--'000015'
----SELECT * FROM tClUbiGeo WHERE CodUbigeoTipo = 'ESTA' 
--if(len(@ef)<>0)
--	begin
--		set @RFC_OUT=LTRIM(RTRIM(@RFC_OUT))+@ef
--	end
--	else
--	begin
--		set @RFC_OUT=LTRIM(RTRIM(@RFC_OUT))+'NE'
--	end

--/*criterior de excepcion*/
--set @RFC_OUT=replace(@RFC_OUT,'/','X')
--set @RFC_OUT=replace(@RFC_OUT,'-','X')
--set @RFC_OUT=replace(@RFC_OUT,'.','X')
--set @RFC_OUT=replace(@RFC_OUT,'´','X')

----Posiciones 14-16
--declare @p char(1)
--declare @m char(1)
--declare @n char(1)

--SET @APATERNO1_LONGITUD= LEN(@APATERNO1)
--SET @VARLOOPS = 1 --EMPIEZA EN UNO POR LA PRIMERA LETRA SE LA VA A SALTAR
--WHILE @APATERNO1_LONGITUD > @VARLOOPS
--BEGIN
--	SET @VARLOOPS = @VARLOOPS + 1
--	IF SUBSTRING(@APATERNO1,@VARLOOPS,1) IN ('B','C','D','F','G','H','J','K','L','M','Ñ','N','P','Q','R','S','T','V','W','X','Y','Z')
--	BEGIN
--		SET @p = CONVERT(CHAR(1),SUBSTRING(@APATERNO1,@VARLOOPS,1))
--		SET @VARLOOPS = @APATERNO1_LONGITUD
--	END
--END
--if(@p<>'') begin set @RFC_OUT=LTRIM(RTRIM(@RFC_OUT))+@p end
--else begin set @RFC_OUT=LTRIM(RTRIM(@RFC_OUT))+'X' end

--SET @AMATERNO1_LONGITUD= LEN(@AMATERNO1)
--SET @VARLOOPS = 1 --EMPIEZA EN UNO POR LA PRIMERA LETRA SE LA VA A SALTAR
--WHILE @AMATERNO1_LONGITUD > @VARLOOPS
--BEGIN
--	SET @VARLOOPS = @VARLOOPS + 1
--	IF SUBSTRING(@AMATERNO1,@VARLOOPS,1) IN ('B','C','D','F','G','H','J','K','L','M','Ñ','N','P','Q','R','S','T','V','W','X','Y','Z')
--	BEGIN
--		SET @m = CONVERT(CHAR(1),SUBSTRING(@AMATERNO1,@VARLOOPS,1))
--		SET @VARLOOPS = @AMATERNO1_LONGITUD
--	END
--END
--if(@m<>'') begin set @RFC_OUT=LTRIM(RTRIM(@RFC_OUT))+@m end
--else begin set @RFC_OUT=LTRIM(RTRIM(@RFC_OUT))+'X' end

--SET @NOMBRE1_LONGITUD= LEN(@NOMBRE1)
--SET @VARLOOPS = 1 --EMPIEZA EN UNO POR LA PRIMERA LETRA SE LA VA A SALTAR
--WHILE @NOMBRE1_LONGITUD > @VARLOOPS
--BEGIN
--	SET @VARLOOPS = @VARLOOPS + 1
--	IF SUBSTRING(@NOMBRE1,@VARLOOPS,1) IN ('B','C','D','F','G','H','J','K','L','M','Ñ','N','P','Q','R','S','T','V','W','X','Y','Z')
--	BEGIN
--		SET @n = CONVERT(CHAR(1),SUBSTRING(@NOMBRE1,@VARLOOPS,1))
--		SET @VARLOOPS = @NOMBRE1_LONGITUD
--	END
--END
--if(@n<>'') begin set @RFC_OUT=LTRIM(RTRIM(@RFC_OUT))+@n end
--else begin set @RFC_OUT=LTRIM(RTRIM(@RFC_OUT))+'X' end

--if(charindex('Ñ',@RFC_OUT,14)<>0) set @RFC_OUT = substring(@RFC_OUT,1,13)+replace(substring(@RFC_OUT,14,5),'Ñ','X')

--select @RFC_OUT RFC

return (@RFC_OUT)
end
--UIMC790918HNERNH04
--UIMC790918HNERNH
GO

GRANT EXECUTE ON [dbo].[fduCalculoCURP2017_10] TO [rie_jaguilar]
GO

GRANT EXECUTE ON [dbo].[fduCalculoCURP2017_10] TO [rie_sbravoa]
GO

GRANT EXECUTE ON [dbo].[fduCalculoCURP2017_10] TO [rie_ldomingueze]
GO

GRANT EXECUTE ON [dbo].[fduCalculoCURP2017_10] TO [rie_jalvarezc]
GO

GRANT EXECUTE ON [dbo].[fduCalculoCURP2017_10] TO [rie_blozanob]
GO