CREATE TABLE [dbo].[tCsRptTCPagosxSucursal] (
  [fecha] [smalldatetime] NULL,
  [sucursal] [varchar](200) NULL,
  [d1] [money] NULL,
  [d2] [money] NULL,
  [d3] [money] NULL,
  [d4] [money] NULL,
  [d5] [money] NULL,
  [d6] [money] NULL,
  [d7] [money] NULL,
  [d8] [money] NULL,
  [d9] [money] NULL,
  [d10] [money] NULL,
  [d11] [money] NULL,
  [d12] [money] NULL,
  [d13] [money] NULL,
  [d14] [money] NULL,
  [d15] [money] NULL,
  [d16] [money] NULL,
  [d17] [money] NULL,
  [d18] [money] NULL,
  [d19] [money] NULL,
  [d20] [money] NULL,
  [d21] [money] NULL,
  [d22] [money] NULL,
  [d23] [money] NULL,
  [d24] [money] NULL,
  [d25] [money] NULL,
  [d26] [money] NULL,
  [d27] [money] NULL,
  [d28] [money] NULL,
  [d29] [money] NULL,
  [d30] [money] NULL,
  [d31] [money] NULL
)
ON [PRIMARY]
GO