CREATE TABLE [dbo].[Regulatorio_0452_mes_anterior] (
  [codprestamo] [varchar](30) NULL,
  [Reporte] [varchar](30) NULL,
  [xIDENTIFICADORCNBV] [varchar](40) NULL,
  [NumeroDisposicion] [int] NULL,
  [ClasificacionContable] [varchar](30) NULL,
  [FechaCorte] [varchar](30) NULL,
  [SaldoIndolutoInicialFC] [money] NULL,
  [MontoDispuestoFC] [money] NULL,
  [MontoIntOrdinariosFC] [money] NULL,
  [MontoIntMoratoriosFC] [money] NULL,
  [MontoComisionesFC] [money] NULL,
  [MontoIVAFC] [money] NULL,
  [MontoPaExCapFC] [money] NULL,
  [MontoPaExIntFC] [money] NULL,
  [MontoPaExComFC] [money] NULL,
  [MontoCapPagadoFC] [money] NULL,
  [MontoIntPagadoFC] [money] NULL,
  [MontoMorPagadoFC] [money] NULL,
  [MontoComPagadoFC] [money] NULL,
  [MontoOtrosAccPagadoFC] [money] NULL,
  [TasaOrdAnualFC] [money] NULL,
  [TasaMorAnualFC] [money] NULL,
  [SaldoIndolutoFC] [money] NULL,
  [FechaUltDisposicion] [varchar](30) NULL,
  [PlazoVctoLineaCredOri] [varchar](30) NULL,
  [SaldoPrinInicioPeriodo] [money] NULL,
  [MontoDispuestoLineaCredIniMes] [money] NULL,
  [CreditoDisponibleLineaCred] [money] NULL,
  [TasaOrdPeriodo] [money] NULL,
  [TasaMorPeriodo] [money] NULL,
  [MontoIntOrdPeriodo] [money] NULL,
  [MontoIntMorPeriodo] [money] NULL,
  [MontoIntRefinRecaPeriodo] [money] NULL,
  [MontoIntReversoCobrosPeriodo] [money] NULL,
  [SaldoBaseCalcIntPeriodo] [money] NULL,
  [NumDiasUtilizaCalcIntPeriodo] [int] NULL,
  [ComisionesPeriodo] [money] NULL,
  [MontoCondonaPeriodo] [money] NULL,
  [MontoQuitaCastigoPeriodo] [money] NULL,
  [MontoBonoEFPeriodo] [money] NULL,
  [MontoRecDescuentoPeriodo] [money] NULL,
  [MontoAumeDecrPrincipalPeriodo] [money] NULL,
  [MontoCapPagadoPeriodo] [money] NULL,
  [MontoIntPagadoPeriodo] [money] NULL,
  [MontoMorPagadoPeriodo] [money] NULL,
  [MontoComPagadoPeriodo] [money] NULL,
  [MontoOtrosAccPagadoPeriodo] [money] NULL,
  [MontoTotalPagadoPeriodo] [money] NULL,
  [SaldoPrincipalFinalPeriodo] [money] NULL,
  [SaldoInsolutoFinalPeriodo] [money] NULL,
  [SituacionCredito] [int] NULL,
  [TipoRecuperacion] [int] NULL,
  [NumeroDiasMora] [int] NULL,
  [FechaUltPagoCompleto] [varchar](30) NULL,
  [MontoUltPagoCompleto] [money] NULL,
  [FechaPrimeraAmorNoCubierta] [varchar](30) NULL,
  [TipoGarantia] [int] NULL,
  [NumeroGarantias] [int] NULL,
  [ProgramaCredGobiernoFederal] [int] NULL,
  [MontoGarantia] [money] NULL,
  [PorcentajeReprGarantiaSaldoInsoluto] [money] NULL,
  [GradoPrelacionGarantia] [int] NULL,
  [FechaValuacionGarantia] [varchar](30) NULL,
  [NumeroAvales] [int] NULL,
  [PorcentajeGarantizaAval] [money] NULL,
  [NombreAval] [varchar](50) NULL,
  [RFCaval] [varchar](50) NULL,
  [TipoCarteraCalifica] [int] NULL,
  [CalificaCubierta] [varchar](50) NULL,
  [Calificaexpuesta] [varchar](50) NULL,
  [ZonaMarginada] [int] NULL,
  [ClavePrevencion] [varchar](50) NULL,
  [FuenteFondeo] [int] NULL,
  [PorceEPMontoCubierto] [money] NULL,
  [MontoCreditoCubierto] [money] NULL,
  [MontoEPCubierto] [money] NULL,
  [PorceEPMontoExpuesto] [money] NULL,
  [MontoCreditoExpuesto] [money] NULL,
  [MontoEPExpuesto] [money] NULL,
  [MontoEPTotalesCalifica] [money] NULL,
  [MontoEPadicionalRO] [money] NULL,
  [MontoEPadicionalIntDevNoCobradosVencidosBalance] [money] NULL,
  [MontoEPadicionalCNBV] [money] NULL,
  [MontoEPadicionalTotal] [money] NULL,
  [MontoEPadicionalIntDevNoCobradosVencidosCtaOrden] [money] NULL,
  [EPTotalesDerivadasCalificaMesInmediatoAnterior] [money] NULL
)
ON [PRIMARY]
GO

GRANT SELECT ON [dbo].[Regulatorio_0452_mes_anterior] TO [rie_sbravoa]
GO

GRANT SELECT ON [dbo].[Regulatorio_0452_mes_anterior] TO [rie_ldomingueze]
GO

GRANT
  DELETE,
  INSERT,
  SELECT,
  UPDATE
ON [dbo].[Regulatorio_0452_mes_anterior] TO [rie_jalvarezc]
GO

GRANT SELECT ON [dbo].[Regulatorio_0452_mes_anterior] TO [rie_blozanob]
GO