CREATE TABLE [dbo].[tSHFOtorgamiento] (
  [ReporteInicio] [smalldatetime] NOT NULL,
  [ReporteFin] [smalldatetime] NOT NULL,
  [Emisor] [varchar](3) NULL,
  [LineaNegocio] [int] NOT NULL,
  [TipoTransaccion] [int] NULL,
  [TipoEnvio] [char](1) NULL,
  [idLineaCredito] [varchar](10) NULL,
  [Originador] [varchar](3) NULL,
  [SolucionVivienda] [varchar](13) NULL,
  [CodPrestamo] [varchar](25) NOT NULL,
  [CodUsuario] [varchar](15) NOT NULL,
  [CodOficina] [varchar](4) NULL,
  [Monto] [decimal](16, 4) NULL,
  [Divisa] [int] NULL,
  [Frecuencia] [int] NULL,
  [MontoPago] [money] NULL,
  [Desembolso] [smalldatetime] NULL,
  [Mininistracion] [smalldatetime] NULL,
  [Vencimiento] [smalldatetime] NULL,
  [Destino] [int] NULL,
  [Plazo] [int] NULL,
  [cveIC] [int] NOT NULL,
  [valIC] [decimal](21, 10) NULL,
  [cveIM] [int] NOT NULL,
  [valIM] [decimal](21, 10) NULL,
  [cveCA] [int] NOT NULL,
  [valCA] [decimal](38, 4) NULL,
  [cveCM] [int] NULL,
  [valCM] [decimal](38, 4) NULL,
  [Nombres] [varchar](80) NULL,
  [Paterno] [varchar](50) NULL,
  [Materno] [varchar](50) NULL,
  [Genero] [char](1) NULL,
  [Nacimiento] [smalldatetime] NULL,
  [EstadoCivil] [int] NULL,
  [Estudios] [int] NULL,
  [Dependientes] [int] NOT NULL,
  [TipoPropeidad] [int] NULL,
  [Antiguedad] [int] NULL,
  [Municipio] [varchar](5) NULL,
  [TipoEmpleo] [int] NOT NULL,
  [Ingresos] [decimal](38, 4) NULL,
  [DeudaTotal] [decimal](38, 4) NULL,
  [IngresosConyuge] [decimal](20, 4) NULL,
  [DeudaConyuge] [decimal](38, 4) NOT NULL,
  CONSTRAINT [PK_tSHFOtorgamiento] PRIMARY KEY CLUSTERED ([ReporteInicio], [ReporteFin], [CodPrestamo], [CodUsuario])
)
ON [PRIMARY]
GO