CREATE TABLE [dbo].[tCaReporteKPI] (
  [fecha] [smalldatetime] NOT NULL,
  [region] [varchar](50) NOT NULL,
  [nomoficina] [varchar](50) NOT NULL,
  [tipoSucursal] [varchar](10) NOT NULL,
  [saldo0a30Ini] [money] NULL,
  [saldo31a89Ini] [money] NULL,
  [saldo90Ini] [money] NULL,
  [saldocapIni] [money] NULL,
  [saldo0a30Fin] [money] NULL,
  [saldo31a89Fin] [money] NULL,
  [saldo90Fin] [money] NULL,
  [saldoCastigado] [money] NULL,
  [saldocapFinal] [money] NULL,
  [var0a30] [money] NULL,
  [var31a89] [money] NULL,
  [var90] [money] NULL,
  [carteraTotal] [money] NULL,
  [cartVencidaIni] [money] NULL,
  [cartVencidaFin] [money] NULL,
  [varCapVencido] [money] NULL,
  [PtmosVigIni] [int] NULL,
  [PtmosVigFin] [int] NULL,
  [varClientes] [int] NULL,
  [metacliente] [int] NULL,
  [porCliente] [decimal](27, 9) NULL,
  [Imor1] [money] NULL,
  [Imor8] [money] NULL,
  [Imor16] [money] NULL,
  [Imor30] [money] NULL,
  [Imor31] [money] NULL,
  [Imor90] [money] NULL,
  [metaCrecimiento] [money] NULL,
  [porCrecimiento] [money] NULL,
  [montoColocacion] [money] NULL,
  [porColocacion] [money] NULL,
  [porAnticipado_Cobrza] [money] NULL,
  [porOrganico_Cobrza] [money] NULL,
  [portotalCobrza] [money] NULL,
  [CapitalProgramado] [money] NULL,
  [CapitalCobrado] [money] NULL,
  [pagP_1] [int] NULL,
  [totalCiclo1] [money] NULL,
  [capCiclo1] [money] NULL,
  [pagP_2] [int] NULL,
  [totalCiclo2] [money] NULL,
  [capCiclo2] [money] NULL,
  [pagP_3a4] [int] NULL,
  [totalCiclo3a4] [money] NULL,
  [capCiclo3a4] [money] NULL,
  [totalCiclo5] [money] NULL,
  [capCiclo5] [money] NULL,
  [RenovAntDisper] [money] NULL,
  [ReactivacionDisper] [money] NULL,
  [RenovDisper] [money] NULL,
  [nuevoDisper] [money] NULL,
  [montoDispersion] [money] NULL,
  [RenovAntEnt] [money] NULL,
  [ReactEnt] [money] NULL,
  [RenovEnt] [money] NULL,
  [nuevoEnt] [money] NULL,
  [montoEntrega] [money] NULL,
  [nuevosPtmos] [int] NULL,
  [porDispersion] [money] NULL,
  [porEntrega] [money] NULL,
  [nroAnticipadas] [int] NULL,
  [montoAnticipadas] [money] NULL,
  [nroPendienteRenov] [int] NULL,
  [PendienteRenov] [money] NULL,
  [poralcanceRenov] [money] NULL,
  [porClientesRenov] [decimal](27, 9) NULL,
  [porAlcaReactivacion] [decimal](38, 4) NULL,
  [montPendReactivacion] [money] NULL,
  [nroPendReactivacion] [int] NULL,
  [mes0a3] [int] NULL,
  [mes3a6] [int] NULL,
  [mes6a9] [int] NULL,
  [mes9a12] [int] NULL,
  [mes12] [int] NULL,
  [totSucursal] [int] NULL,
  [vacante] [int] NULL,
  [capProgra1] [money] NULL,
  [capProgra2] [money] NULL,
  [capProgra3a4] [money] NULL,
  [capProgra5] [money] NULL,
  [CapitalPagado] [money] NULL,
  [capPagado1] [money] NULL,
  [capPagado2] [money] NULL,
  [capPagado3a4] [money] NULL,
  [capPagado5] [money] NULL,
  [RenovPtmos] [int] NULL,
  [RAnticipaPtmos] [int] NULL,
  [ReactivaPtmos] [int] NULL,
  [totaPtmos] [int] NULL,
  [promRenovColoca] [money] NULL,
  [promRAnticipaColoca] [money] NULL,
  [promReactivaColoca] [money] NULL,
  [promNuevoColoca] [money] NULL,
  [promTotalColoca] [money] NULL,
  [porRenov] [money] NULL,
  [porRAnticipa] [money] NULL,
  [porReactiva] [money] NULL,
  [porNuevo] [money] NULL,
  [porTotal] [money] NULL,
  [MontoRenov] [money] NULL,
  [ptmosRenov] [int] NULL,
  [montoLiqui] [money] NULL,
  [ptmsLiqui] [int] NULL
)
ON [PRIMARY]
GO

GRANT SELECT ON [dbo].[tCaReporteKPI] TO [Int_dreyesg]
GO