CREATE TABLE [dbo].[tUsUsuarioRH] (
  [CodUsuario] [char](15) NOT NULL,
  [FechaIngreso] [smalldatetime] NULL,
  [CodCargo] [varchar](4) NULL,
  [Funcion] [varchar](50) NULL,
  [Profesion] [varchar](50) NULL,
  [CodTipoContrato] [char](3) NULL,
  [ContFechaInicio] [datetime] NULL,
  [FechaCalcFini] [datetime] NULL,
  [ContFechaVence] [datetime] NULL,
  [ContCodMoneda] [varchar](2) NULL CONSTRAINT [DF_tUsUsuarioRH_ContCodMoneda] DEFAULT ('1'),
  [CodMatrizSal] [int] NULL,
  [SueldoBasico] [money] NOT NULL CONSTRAINT [DF_tUsUsuarioRH_SueldoBasico] DEFAULT (0),
  [EsMensual] [bit] NULL CONSTRAINT [DF_tUsUsuarioRH_EsMensual] DEFAULT (1),
  [AbonoAutomatico] [bit] NULL CONSTRAINT [DF_tUsUsuarioRH_AbonoAutomatico] DEFAULT (1),
  [CodEntidadTipo] [varchar](3) NULL,
  [CodEntidad] [varchar](3) NULL,
  [CuentaEntidad] [varchar](25) NULL,
  [CodEntidadTipoD] [varchar](3) NULL,
  [CodEntidadD] [varchar](3) NULL,
  [CuentaEntidadD] [varchar](25) NULL,
  [ParticipaEnPrima] [bit] NOT NULL CONSTRAINT [DF_tUsUsuarioRH_ParticipaEnPrima] DEFAULT (0),
  [CodAFP] [char](3) NOT NULL CONSTRAINT [DF_tUsUsuarioRH_CodAFP] DEFAULT (''),
  [FechaAfiliaAFP] [smalldatetime] NULL,
  [CodAfiliaAFP] [varchar](20) NULL,
  [DatosFamilia] [varchar](100) NULL,
  [DatosEmergencia] [varchar](100) NULL,
  [Curriculum] [varchar](250) NULL,
  [xNivel] [varchar](5) NULL,
  [xRango] [char](1) NULL,
  [xAseguradora] [varchar](50) NULL,
  [xNroAsegCaja] [varchar](15) NULL,
  [xFechaAfiliaCaja] [datetime] NULL,
  [xFechaVigenciaAseg] [datetime] NULL,
  [xObsAseguradora] [varchar](250) NULL,
  [xNroAsegConyuge] [varchar](12) NULL,
  [xFechaAfiliaConyuge] [datetime] NULL,
  [xBonoFrontera] [bit] NULL CONSTRAINT [DF_tUsUsuarioRH_xBonoFrontera] DEFAULT (0),
  [xEnPlanillaSueldos] [bit] NOT NULL CONSTRAINT [DF_tUsUsuarioRH_xEnPlanillaSueldos] DEFAULT (1),
  [IdGradoIns] [tinyint] NULL,
  [NroDiasContrato] [int] NULL,
  [CodFondo] [varchar](2) NULL,
  [CtaAhorro] [varchar](50) NULL,
  [CtaCTS] [varchar](50) NULL,
  [EsRentista] [bit] NULL,
  [MontoReserva] [money] NULL,
  [AnticipoFijo] [money] NULL,
  CONSTRAINT [PK_tUsUsuarioRH] PRIMARY KEY CLUSTERED ([CodUsuario])
)
ON [PRIMARY]
GO