CREATE TABLE [dbo].[tmpPagIntPerFeb2021] (
  [Fecha] [smalldatetime] NOT NULL,
  [CodigoCuenta] [varchar](25) NOT NULL,
  [FraccionCta] [varchar](8) NOT NULL,
  [Renovado] [tinyint] NOT NULL,
  [CodSistema] [char](2) NOT NULL,
  [TranHora] [char](2) NULL,
  [TranMinuto] [char](2) NULL,
  [TranSegundo] [char](2) NULL,
  [TranMicroSegundo] [smallint] NULL,
  [CodOficina] [varchar](4) NOT NULL,
  [CodOficinaCuenta] [varchar](4) NULL,
  [NroTransaccion] [varchar](10) NOT NULL,
  [TipoTransacNivel1] [char](1) NOT NULL,
  [TipoTransacNivel2] [varchar](10) NOT NULL,
  [TipoTransacNivel3] [tinyint] NOT NULL,
  [Extornado] [bit] NULL,
  [TipoCambio] [decimal](9, 5) NULL,
  [NombreCliente] [varchar](200) NULL,
  [DescripcionTran] [varchar](1000) NULL,
  [CodCajero] [varchar](15) NULL,
  [CodMoneda] [tinyint] NULL,
  [MontoCapitalTran] [money] NULL,
  [MontoInteresTran] [money] NULL,
  [MontoINVETran] [money] NULL,
  [MontoINPETran] [money] NULL,
  [MontoCargos] [money] NULL,
  [MontoOtrosTran] [money] NULL,
  [MontoImpuestos] [money] NULL,
  [MontoTotalTran] [money] NULL,
  [FechaApertura] [smalldatetime] NULL,
  [FechaVencimiento] [smalldatetime] NULL,
  [CodBanco] [varchar](30) NULL,
  [NroCuenta] [varchar](30) NULL,
  [NroCheque] [varchar](30) NULL,
  [NroSecuencial] [int] NULL,
  [CodMotivo] [int] NULL,
  [CodUsuario] [varchar](15) NOT NULL,
  [CodAsesor] [varchar](15) NULL,
  [CodProducto] [char](10) NULL,
  [CodDestino] [varchar](15) NULL,
  [CodTipoCredito] [tinyint] NULL,
  [MontoDescontado] [smallmoney] NULL,
  [Secuencia] [int] NULL,
  [TasaInteres] [decimal](19, 4) NULL,
  [Sistemas] [int] NULL
)
ON [PRIMARY]
GO