CREATE TABLE [dbo].[JudicialExtra] (
  [Nro] [float] NULL,
  [CodOficina] [float] NULL,
  [Observacion] [varchar](50) NULL,
  [Dato] [varchar](4000) NULL,
  [ClienteGrupo] [varchar](1) NULL,
  [CoincidenciaBase] [varchar](100) NULL,
  [CodPrestamo] [varchar](25) NULL,
  [CodUsuario] [varchar](15) NULL,
  [FechaDesembolso] [smalldatetime] NULL,
  [Desembolso] [decimal](18, 4) NULL,
  [NroCuotas] [int] NULL,
  [Estado] [varchar](50) NULL,
  [FechaCastigo] [smalldatetime] NULL,
  [CapitalCastigado] [decimal](18, 4) NULL,
  [InteresCastigadoVig] [decimal](18, 4) NULL,
  [InteresCastigadoVen] [decimal](18, 4) NULL,
  [InteresCastigadoOrd] [decimal](18, 4) NULL,
  [MoratorioCastigadoVig] [decimal](18, 4) NULL,
  [MoratorioCastigadoVen] [decimal](18, 4) NULL,
  [MoratorioCastigadoOrd] [decimal](18, 4) NULL,
  [MoraCastigada] [decimal](18, 4) NULL,
  [OtrosCargosCastigado] [decimal](18, 4) NULL,
  [ImpuestosCastigado] [decimal](18, 4) NULL,
  [TotalCastigada] [decimal](27, 4) NULL,
  [CorteInicial] [smalldatetime] NULL,
  [CapitalCierre] [decimal](18, 4) NULL,
  [InteresCierreVig] [decimal](18, 4) NULL,
  [InteresCierreVen] [decimal](18, 4) NULL,
  [InteresCierreOrd] [decimal](18, 4) NULL,
  [MoratorioCierreVig] [decimal](18, 4) NULL,
  [MoratorioCierreVen] [decimal](18, 4) NULL,
  [MoratorioCierreOrd] [decimal](18, 4) NULL,
  [MoraCierre] [decimal](18, 4) NULL,
  [OtrosCargosCierre] [decimal](18, 4) NULL,
  [ImpuestosCierre] [decimal](18, 4) NULL,
  [TotalCierre] [decimal](27, 4) NULL,
  [CorteFinal] [smalldatetime] NULL,
  [CapitalActual] [decimal](18, 4) NULL,
  [InteresActualVig] [decimal](18, 4) NULL,
  [InteresActualVen] [decimal](18, 4) NULL,
  [InteresActualOrd] [decimal](18, 4) NULL,
  [MoratorioActualVig] [decimal](18, 4) NULL,
  [MoratorioActualVen] [decimal](18, 4) NULL,
  [MoratorioActualOrd] [decimal](18, 4) NULL,
  [MoraActual] [decimal](18, 4) NULL,
  [OtrosCargosActual] [decimal](18, 4) NULL,
  [ImpuestosActual] [decimal](18, 4) NULL,
  [TotalActual] [decimal](27, 4) NULL,
  [CapitalPago] [decimal](18, 4) NULL,
  [InteresPago] [decimal](18, 4) NULL,
  [MoratorioPago] [decimal](18, 4) NULL,
  [MoraPago] [decimal](18, 4) NULL,
  [OtrosCargosPago] [decimal](18, 4) NULL,
  [ImpuestosPago] [decimal](18, 4) NULL,
  [TotalPago] [decimal](23, 4) NULL,
  [FechaCancelacion] [smalldatetime] NULL,
  [FechaCorte] [smalldatetime] NULL,
  [DeudaTotal] [decimal](18, 4) NULL,
  [CierreEnero] [decimal](18, 4) NULL,
  [PagoALaFecha] [decimal](18, 4) NULL
)
ON [PRIMARY]
GO