CREATE TABLE [dbo].[_AH0841] (
  [periodo] [varchar](10) NULL,
  [claveentidad] [varchar](6) NOT NULL,
  [reporte] [varchar](3) NOT NULL,
  [codusuario] [varchar](15) NULL,
  [nombres] [varchar](8000) NULL,
  [paterno] [varchar](50) NULL,
  [materno] [varchar](50) NULL,
  [PersonalidadJuridica] [int] NOT NULL,
  [GradoRiesgo] [varchar](11) NOT NULL,
  [actividad] [varchar](5) NOT NULL,
  [Nacionalidad] [int] NOT NULL,
  [fechanacimiento] [varchar](50) NULL,
  [usrfc] [varchar](20) NULL,
  [uscurp] [varchar](20) NULL,
  [genero] [int] NOT NULL,
  [calle] [varchar](150) NULL,
  [numexterior] [varchar](10) NULL,
  [Colonia] [varchar](60) NULL,
  [codpostal] [varchar](10) NULL,
  [Localidad] [varchar](15) NULL,
  [Municipio] [int] NULL,
  [Estado] [int] NULL,
  [PaisDomicilio] [int] NOT NULL,
  [ClaveSucursal] [varchar](4) NULL,
  [numcuenta] [varchar](39) NULL,
  [numcontrato] [varchar](39) NULL,
  [TipoCliente] [int] NOT NULL,
  [ClasificacionContable] [varchar](12) NOT NULL,
  [ClasificacionCertBursatil] [varchar](8) NOT NULL,
  [TipoProducto] [varchar](5) NOT NULL,
  [fechaapertura] [varchar](50) NULL,
  [fechaprimerdeposito] [varchar](50) NULL,
  [montoprimerdepositoOrigen] [money] NULL,
  [montoprimerdepositoPesos] [money] NULL,
  [fechavencimiento] [varchar](50) NULL,
  [plazovencimiento] [numeric](10) NULL,
  [RangoPlazo] [int] NOT NULL,
  [PeriocidadRend] [int] NOT NULL,
  [TipoTasa] [int] NOT NULL,
  [ValorTasaOri] [money] NULL,
  [ValorTasaPeriodo] [money] NULL,
  [TasaIntReferencia] [int] NOT NULL,
  [DiferencialTasaReferencia] [int] NOT NULL,
  [OperacionDiferencial] [int] NOT NULL,
  [FrecuenciaRevisionTasa] [int] NOT NULL,
  [TipoMoneda] [int] NOT NULL,
  [saldocuenta] [money] NULL,
  [Montodepósito] [money] NULL,
  [Montoretiro] [money] NULL,
  [IntDevenoPag] [money] NULL,
  [SaldoFinalPeriodo] [money] NULL,
  [DevengadoMes] [money] NULL,
  [ComisionesMes] [int] NOT NULL,
  [FechaUltimoMovi] [datetime] NULL,
  [MontoUltimoMovi] [money] NULL,
  [saldopromedio] [money] NULL,
  [RetiroAntDeposito] [varchar](3) NOT NULL,
  [PENDIENTE MntoCubFProteccion] [int] NOT NULL,
  [PENDIENTE PorcCubFProteccion] [int] NOT NULL,
  [PENDIENTE PorcGarantia] [int] NOT NULL
)
ON [PRIMARY]
GO