CREATE TABLE [dbo].[tCsUnisapCartera] (
  [Fecha] [smalldatetime] NULL,
  [Ano] [float] NULL,
  [Mes] [char](8) NULL,
  [Nombre Acreditado] [nvarchar](255) NULL,
  [NroClientes] [float] NULL,
  [NroPtmos] [float] NULL,
  [CodigoCliente] [nvarchar](255) NULL,
  [CodOficina] [float] NULL,
  [Oficina] [nvarchar](255) NULL,
  [EstadoGeo] [nvarchar](255) NULL,
  [Producto] [float] NULL,
  [NodeContrato] [nvarchar](255) NULL,
  [Tecnologia] [nvarchar](255) NULL,
  [CodAsesor] [nvarchar](255) NULL,
  [NombredeAsesor] [nvarchar](255) NULL,
  [EsBis] [nvarchar](255) NULL,
  [Tipo Credito] [nvarchar](255) NULL,
  [Condociones de Pago] [nvarchar](255) NULL,
  [FechaOtorgamiento] [smalldatetime] NULL,
  [MontoOriginal] [float] NULL,
  [FechaVencimiento] [smalldatetime] NULL,
  [TasaONA%] [float] NULL,
  [TasaOMA%] [float] NULL,
  [NoCuotas] [float] NULL,
  [Frecuencia] [nvarchar](255) NULL,
  [RangoDias] [nvarchar](255) NULL,
  [Dias Mora] [float] NULL,
  [SaldoCapital] [float] NULL,
  [CapitalVigente] [float] NULL,
  [CapitalVencido] [float] NULL,
  [InteresVigente] [float] NULL,
  [InteresVencido] [float] NULL,
  [CuentasdeOrden] [float] NULL,
  [SaldoPromedioDiariodelMes] [float] NULL,
  [InteresdelMes] [float] NULL,
  [ReservaPreventivaCreadaAsociadaalPtmo] [float] NULL,
  [ReservaPreventivaCreada100%InteresesTraspaso] [float] NULL,
  [FechaultimoPagoCapital] [datetime] NULL,
  [FechaultimoPagoInteres] [datetime] NULL,
  [MontoultimoPagoCapital] [float] NULL,
  [MontoultimoPagoInteres] [float] NULL,
  [EstadoPtmo] [nvarchar](255) NULL,
  [RenovadoRestructuradoNormal] [nvarchar](255) NULL,
  [NumerodeReestructuras] [float] NULL,
  [TipodeGarantia] [nvarchar](255) NULL,
  [ValorGarantia] [float] NULL,
  [Formalizada (Si/No)] [nvarchar](255) NULL,
  [Fondo] [nvarchar](255) NULL,
  [EstimacionPreventiva] [float] NULL,
  [ComisionDesembolso] [float] NULL,
  [FechaAltaAsesor] [datetime] NULL,
  [FechaBajaAsesor] [datetime] NULL
)
ON [PRIMARY]
GO