CREATE TABLE [dbo].[tCaDesembVerificacionFisica] (
  [FechaDesembolso] [smalldatetime] NULL,
  [codprestamo] [varchar](30) NULL,
  [codsolicitud] [varchar](15) NULL,
  [codoficina] [varchar](4) NULL,
  [codusuario] [varchar](30) NULL,
  [observacion] [varchar](300) NULL,
  [conactividad] [tinyint] NULL,
  [conreside] [tinyint] NULL,
  [conCompDomicilio] [tinyint] NULL,
  [conDocIdentidad] [tinyint] NULL,
  [codParentescoCompDom] [varchar](3) NULL,
  [coordenada] [tinyint] NULL,
  [Longitud] [decimal](20, 8) NULL,
  [Latitud] [decimal](20, 8) NULL,
  [Monto] [money] NULL,
  [Producto] [int] NULL,
  [DestinoCredito] [int] NULL,
  [ActividadEconimica] [varchar](500) NULL,
  [TiempoActividad] [int] NULL,
  [NombreJefe] [varchar](200) NULL,
  [GastoNegocio] [money] NULL,
  [CprobanteIngresos] [int] NULL,
  [Domicilio] [varchar](800) NULL,
  [AnosDom] [int] NULL,
  [DomNegocio] [varchar](800) NULL,
  [Referencia1] [varchar](800) NULL,
  [Referencia2] [varchar](800) NULL,
  [Comentarios] [varchar](1000) NULL,
  [Ciclo] [int] NULL,
  [GastoPersonal] [money] NULL,
  [IngresoMensual] [money] NULL,
  [ComentarioAreaCredito] [varchar](1000) NULL,
  [Verificador] [varchar](50) NULL,
  [Recomienda] [varchar](3) NULL,
  [AnosNego] [varchar](4) NULL,
  [Telefono1] [varchar](10) NULL,
  [Telefono2] [varchar](10) NULL,
  [Cuotas] [varchar](5) NULL,
  [FechaHora] [varchar](20) NULL,
  [Plazo] [varchar](2) NULL,
  [FechaUltVerificacion] [smalldatetime] NULL,
  [ParetescoRef1] [varchar](800) NULL,
  [ParetescoRef2] [varchar](800) NULL,
  [DireccionRef1] [varchar](80) NULL,
  [ComentarioRef1] [varchar](100) NULL,
  [DireccionRef2] [varchar](80) NULL,
  [ComentarioRef2] [varchar](100) NULL
)
ON [PRIMARY]
GO