CREATE TABLE [dbo].[tCsRptBonoCarteraV2] (
  [Fecha] [smalldatetime] NOT NULL,
  [TipoCalculo] [int] NOT NULL,
  [codoficina] [varchar](4) NOT NULL,
  [nomoficina] [varchar](250) NULL,
  [region] [varchar](50) NULL,
  [codasesor] [varchar](15) NOT NULL,
  [nomasesor] [varchar](250) NULL,
  [puesto] [varchar](200) NOT NULL,
  [estadoasesor] [varchar](6) NOT NULL,
  [fechaingreso] [smalldatetime] NULL,
  [codempleado] [varchar](10) NULL,
  [duplicado] [int] NULL,
  [saldocartera] [decimal](16, 2) NULL,
  [saldomayor1dia] [decimal](16, 2) NULL,
  [saldocapital] [decimal](16, 2) NULL,
  [ncliante] [int] NULL,
  [ncliactu] [int] NULL,
  [nnewcliactu] [int] NULL,
  [nrenovado] [int] NULL,
  [nrenovadoM] [int] NULL,
  [nrenovadoFP] [int] NULL,
  [nreasignado] [int] NULL,
  [NumARenovar] [int] NULL,
  [liquidados] [int] NULL,
  [montodesembolso] [decimal](16, 2) NULL,
  [montointeres] [decimal](16, 2) NULL,
  [montointeres2] [decimal](16, 2) NULL,
  [porcen] [decimal](10, 2) NULL,
  [porcen2] [decimal](10, 2) NULL,
  [Bonopagoxinteres] [decimal](28, 4) NULL,
  [moraactual] [decimal](16, 2) NULL,
  [PorRenoClie] [decimal](10, 2) NULL,
  [NetoClientesNuevos] [int] NULL,
  [BonoCrecimientoClientes] [numeric](16, 2) NOT NULL,
  [BonoRenovacionMes] [numeric](27, 2) NULL,
  [PreBono] [decimal](31, 4) NULL,
  [PorcentajeDeduccion] [numeric](16, 2) NOT NULL,
  [BonoFinal] [numeric](38, 6) NULL,
  [MetaProgN] [decimal](18, 6) NULL,
  [MetaProgR] [decimal](18, 6) NULL,
  [MCT] [decimal](23, 6) NULL,
  [MCD] [decimal](22, 6) NULL,
  [PorcMNC] [decimal](16, 2) NULL,
  [PorcMDE] [decimal](16, 2) NULL,
  [BMetaMNC] [decimal](38, 6) NULL,
  [BMetaMDE] [decimal](38, 6) NULL,
  [BONOAPAGAR] [decimal](38, 6) NULL,
  CONSTRAINT [PK_tCsRptBonoCarteraV2] PRIMARY KEY CLUSTERED ([Fecha], [TipoCalculo], [codoficina], [codasesor], [puesto])
)
ON [PRIMARY]
GO

EXEC sys.sp_addextendedproperty N'MS_Description', N'1: individual, 2:solidario, 3: grupal', 'SCHEMA', N'dbo', 'TABLE', N'tCsRptBonoCarteraV2', 'COLUMN', N'TipoCalculo'
GO