CREATE TABLE [dbo].[tCsBUDes] (
  [fecha] [smalldatetime] NOT NULL,
  [archivo] [varchar](50) NOT NULL,
  [no_cuenta] [varchar](25) NOT NULL,
  [rfc] [varchar](25) NOT NULL,
  [id_interno] [float] NOT NULL,
  [duplicada] [nvarchar](255) NULL,
  [nivel_desactualizada] [nvarchar](255) NULL,
  [member_code] [float] NULL,
  [member_kob] [nvarchar](255) NULL,
  [fecha_reporte] [float] NULL,
  [id_expediente] [float] NULL,
  [apellido_paterno] [nvarchar](255) NULL,
  [apellido_materno] [nvarchar](255) NULL,
  [apellido_adicional] [nvarchar](255) NULL,
  [primer_nombre] [nvarchar](255) NULL,
  [segundo_nombre] [nvarchar](255) NULL,
  [fecha_apertura] [float] NULL,
  [tipo_contrato] [nvarchar](255) NULL,
  [tipo_cuenta] [nvarchar](255) NULL,
  [limite_credito] [float] NULL,
  [historico_pago] [varchar](100) NULL,
  [clave_observacion] [nvarchar](255) NULL,
  [forma_pago] [float] NULL,
  [saldo_actual] [float] NULL,
  [saldo_vencido] [float] NULL,
  [importe_pago] [float] NULL,
  [cc_fecha_cierre] [smalldatetime] NULL,
  [cc_saldocuenta] [decimal](16, 4) NULL,
  [cc_saldovencido] [decimal](16, 4) NULL,
  [cc_importepago] [decimal](16, 4) NULL,
  [cc_formapago] [varchar](2) NULL,
  [cc_claveobservacion] [varchar](2) NULL,
  [estado] [varchar](50) NULL,
  CONSTRAINT [PK_tCsBUDes] PRIMARY KEY CLUSTERED ([fecha], [archivo], [no_cuenta], [rfc], [id_interno])
)
ON [PRIMARY]
GO