CREATE TABLE [dbo].[_AltaCancelados] (
  [CodPrestamo] [varchar](25) NOT NULL,
  [CodSolicitud] [varchar](15) NULL,
  [CodProducto] [char](3) NULL,
  [TipoPrestamo] [char](6) NOT NULL,
  [CodAsesor] [char](15) NULL,
  [CodMoneda] [varchar](2) NOT NULL,
  [CodPresAnte] [varchar](25) NULL,
  [CodGrupo] [char](15) NULL,
  [CodUsuario] [char](15) NOT NULL,
  [NumParticip] [smallint] NOT NULL,
  [CodOficina] [varchar](4) NOT NULL,
  [CodUsResp] [char](15) NOT NULL,
  [CodUbiGeo] [varchar](6) NOT NULL,
  [CodFondo] [varchar](2) NOT NULL,
  [CodActividadDes] [varchar](6) NOT NULL,
  [EnLineaCred] [bit] NULL,
  [CodLineaCred] [varchar](25) NULL,
  [CodTipoCre] [char](2) NOT NULL,
  [CodTipoOpe] [char](2) NULL,
  [CodServicioD] [char](6) NULL,
  [NumCuentaD] [char](15) NULL,
  [CodServicioP] [char](6) NULL,
  [NumCuentaP] [char](15) NULL,
  [FechaSolicitud] [datetime] NOT NULL,
  [MontoDesembolso] [money] NOT NULL,
  [MontoConcesional] [money] NOT NULL,
  [MontoDescontado] [money] NULL,
  [CodTipoPlan] [tinyint] NOT NULL,
  [CodTipoCredito] [tinyint] NOT NULL,
  [CodTipoPlaz] [char](1) NOT NULL,
  [Plazo] [int] NOT NULL,
  [Cuotas] [int] NOT NULL,
  [PeriodoConcesional] [int] NOT NULL,
  [VencDiaFijo] [bit] NOT NULL,
  [FechaDiaFijo] [tinyint] NOT NULL,
  [TipoInteres] [char](1) NOT NULL,
  [FechaAprobacion] [datetime] NULL,
  [FechaDesembolso] [datetime] NOT NULL,
  [TipoGarantia] [varchar](5) NOT NULL,
  [TipoCambio] [money] NOT NULL,
  [FechaVencimiento] [datetime] NULL,
  [CodEntidadTipo] [varchar](3) NOT NULL,
  [CodEntidad] [varchar](3) NOT NULL,
  [ProcesarPres] [tinyint] NOT NULL,
  [FechaProceso] [datetime] NOT NULL,
  [TipoEstado] [char](1) NOT NULL,
  [Estado] [varchar](10) NOT NULL,
  [EstadoAnterior] [varchar](10) NOT NULL,
  [FechaEstado] [datetime] NOT NULL,
  [TipoCalificacion] [char](1) NOT NULL,
  [Calificacion] [varchar](3) NOT NULL,
  [CalificacionAnterior] [varchar](3) NOT NULL,
  [FechaCalificacion] [datetime] NOT NULL,
  [FechaProxVen] [datetime] NULL,
  [FechaUltPago] [datetime] NULL,
  [FechaMora] [datetime] NULL,
  [AtrasoAcum] [int] NULL,
  [AtrasoMaximo] [int] NULL,
  [DiasAnio] [smallint] NULL,
  [PagaIntDeven] [bit] NOT NULL,
  [AceptaPagAnt] [bit] NOT NULL,
  [AceptaCanAnt] [bit] NOT NULL,
  [MontoCastigado] [money] NOT NULL,
  [CodMotivo] [tinyint] NULL,
  [FechaCastigo] [datetime] NULL,
  [SoloCuoTotal] [bit] NOT NULL,
  [AceptaPagExt] [bit] NOT NULL,
  [AfectaPagExt] [char](1) NOT NULL,
  [IntReajustab] [bit] NOT NULL,
  [PeriodoReaj] [smallint] NULL,
  [FechaUlReaj] [datetime] NULL,
  [NumReajustes] [smallint] NOT NULL,
  [CodTipoCan] [char](2) NULL,
  [AceptaPago] [bit] NOT NULL,
  [MontoPrevision] [money] NULL,
  [CodAsesorAnt] [char](15) NULL,
  [FechaCambioAsesor] [datetime] NULL,
  [FechaIngMora] [datetime] NULL,
  [CodFondoAnt] [char](2) NOT NULL,
  [FechaPagoSEDES] [datetime] NULL,
  [TEActiva] [money] NOT NULL,
  [TECliente] [money] NOT NULL,
  [GraciaCapital] [smallint] NOT NULL,
  [GraciaInteres] [smallint] NOT NULL,
  [FechaDevNoConINTE] [datetime] NOT NULL,
  [FechaDevConINTE] [datetime] NULL,
  [TipoAfectacion] [tinyint] NULL,
  [DiasMora] [int] NULL,
  [SaldoCapital] [money] NULL,
  [SubEstado] [varchar](30) NULL,
  [AutorizaDesem] [bit] NULL,
  [ConCrediRapido] [bit] NULL,
  [EsCrediRapido] [bit] NULL,
  [CodAnterior] [varchar](27) NOT NULL,
  [TipoReprog] [char](5) NULL,
  [NumReprog] [smallint] NULL,
  [FechaReprog] [datetime] NULL,
  [PrestamoReprog] [varchar](25) NULL,
  [CodPrvmnto] [varchar](3) NULL,
  [CodCuenta] [varchar](25) NOT NULL,
  [FraccionCta] [varchar](8) NOT NULL,
  [Renovado] [tinyint] NOT NULL,
  [DebitoAuto] [bit] NOT NULL,
  [TipoComunal] [char](1) NULL,
  [Ciclo] [varchar](25) NULL,
  [SeContabiliza] [bit] NULL,
  [TipoRecuperacion] [varchar](1) NULL,
  [Correlativo] [int] NOT NULL,
  [CodOficinaFon] [varchar](4) NULL,
  [CodEntidadTipoFon] [varchar](3) NULL,
  [CodEntidadFon] [varchar](3) NULL,
  [NroCuenta] [varchar](30) NULL,
  [CodPrestamoCambProd] [varchar](25) NULL,
  [FlagCambioProducto] [char](1) NULL,
  [DiasMoraAnt] [int] NULL,
  [DiasMoraIni] [int] NOT NULL,
  [SelloElectronico] [varchar](100) NULL,
  [AsesorCarteraVencida] [varchar](20) NULL,
  [FechCambioCarVencida] [datetime] NULL
)
ON [PRIMARY]
GO