CREATE TABLE [dbo].[tCsRptAComerSegCartera] (
  [Fecha] [smalldatetime] NOT NULL,
  [CodPrestamo] [varchar](25) NOT NULL,
  [CodSolicitud] [varchar](15) NULL,
  [CodOficina] [varchar](4) NULL,
  [NomOficina] [varchar](30) NULL,
  [Region] [varchar](50) NULL,
  [CodProducto] [smallint] NULL,
  [NombreProdCorto] [varchar](50) NULL,
  [NombreTec] [varchar](50) NULL,
  [CodAsesor] [varchar](15) NULL,
  [asesor] [varchar](300) NULL,
  [primerpromotor] [varchar](300) NULL,
  [CodUsuario] [varchar](15) NOT NULL,
  [NombreCompleto] [varchar](300) NULL,
  [CodGrupo] [varchar](15) NULL,
  [NombreGrupo] [varchar](50) NULL,
  [Estado] [varchar](50) NULL,
  [SecuenciaSolicitud] [int] NULL,
  [NroDiasAtraso] [int] NULL,
  [NroCuotas] [smallint] NULL,
  [NroCuotasPagadas] [smallint] NULL,
  [NroCuotasPorPagar] [smallint] NULL,
  [FechaDesembolso] [smalldatetime] NULL,
  [FechaVencimiento] [smalldatetime] NULL,
  [MontoDesembolso] [money] NULL,
  [tiporeprog] [char](5) NULL,
  [tipo] [varchar](50) NOT NULL,
  [saldocapital] [money] NOT NULL,
  [capitalvigente] [money] NULL,
  [capitalatrasado] [money] NOT NULL,
  [capitalvencido] [money] NOT NULL,
  [interesvigente] [money] NULL,
  [interesvencido] [money] NULL,
  [interesctaorden] [money] NULL,
  [moratoriovigente] [money] NULL,
  [moratoriovencido] [money] NULL,
  [moratorioctaorden] [money] NULL,
  [otroscargos] [money] NOT NULL,
  [impuestos] [money] NULL,
  [cargomora] [money] NULL,
  [codpostal] [varchar](10) NULL,
  [telefono] [varchar](20) NULL,
  [municipio] [varchar](60) NULL,
  [localidad] [varchar](60) NULL,
  [tasaintcorriente] [decimal](18, 7) NULL,
  [RangoDias] [varchar](15) NULL,
  [Venta] [varchar](14) NOT NULL
)
ON [PRIMARY]
GO