CREATE TABLE [dbo].[tCaClConcepto] (
  [CodConcepto] [varchar](5) NOT NULL,
  [SHF] [varchar](3) NULL,
  [DescConcepto] [varchar](100) NOT NULL,
  [Orden] [tinyint] NOT NULL,
  [TipoConcepto] [char](1) NOT NULL,
  [OrdenAfecta] [smallint] NOT NULL,
  [TipoCobro] [char](1) NOT NULL,
  [ConceptoInicial] [bit] NOT NULL,
  [CalculaDevengado] [bit] NOT NULL,
  [CalculaMora] [bit] NOT NULL,
  [ValorCalculo] [smallint] NOT NULL,
  [ConceptoDeCalculo] [varchar](5) NOT NULL,
  [ModalidadCobro] [char](2) NOT NULL,
  [NumeroPlan] [tinyint] NOT NULL,
  [Factura] [bit] NOT NULL,
  [FacturaPorcen] [money] NOT NULL,
  [CobroSobre] [tinyint] NOT NULL,
  [Activo] [bit] NOT NULL,
  [Pais] [char](1) NOT NULL,
  [NroCuotas] [int] NOT NULL,
  [AfectaSobre] [char](1) NOT NULL,
  [ClaseCobro] [tinyint] NOT NULL,
  [DiasMora] [int] NOT NULL,
  [Valor] [float] NOT NULL,
  [CodMoneda] [char](2) NOT NULL,
  [CodConsEstruc] [varchar](20) NOT NULL,
  [ContaCodigo] [varchar](25) NOT NULL,
  [ContaCodigo1] [varchar](25) NOT NULL,
  [ContaCodigo2] [varchar](25) NOT NULL,
  [TipoCuenta] [varchar](3) NOT NULL,
  [TipoCuenta1] [varchar](3) NOT NULL,
  [TipoCuenta2] [varchar](3) NOT NULL,
  [SeContabiliza] [bit] NOT NULL,
  [CodMedTiempo] [char](2) NOT NULL,
  [Reformulacion] [bit] NOT NULL,
  [TipoContable] [char](1) NULL,
  [MaxCobros] [int] NULL,
  [CobrosSobre] [char](1) NOT NULL,
  [ImporteSobre] [int] NULL,
  [SeContabilizaEstado] [bit] NULL,
  [tc_normal] [bit] NOT NULL,
  [tc_BLinCred] [bit] NOT NULL,
  [tc_ALinCred] [bit] NOT NULL,
  [AplicaBoleta] [bit] NOT NULL,
  [FrecPago] [char](1) NOT NULL,
  [CadaN] [int] NOT NULL,
  [SeContabilizaDevengamiento] [bit] NOT NULL,
  [SeContabilizaOrden] [bit] NOT NULL,
  CONSTRAINT [PK_tCaClConcepto] PRIMARY KEY CLUSTERED ([CodConcepto])
)
ON [PRIMARY]
GO