CREATE TABLE [dbo].[TmpROAlcanceRegion] (
  [fecha] [smalldatetime] NULL,
  [region] [varchar](30) NULL,
  [carteraVgte_inicial] [money] NULL,
  [imor31_inicial] [money] NULL,
  [carteraVgteActual] [money] NULL,
  [imor31_Actual] [money] NULL,
  [MetaCrecimiento] [int] NOT NULL,
  [CRECIMIENTO] [money] NULL,
  [AlcanceCrecimiento] [int] NOT NULL,
  [alcanceCobranza_por] [money] NULL,
  [permanencia_s] [money] NULL,
  [permanencia_n] [decimal](38, 19) NULL,
  [ptmosVigIni] [money] NULL,
  [ptmosVigFin] [money] NULL,
  [metacliente] [int] NOT NULL,
  [montocolocado] [money] NULL,
  [mes0a6] [int] NULL,
  [mes6m] [int] NULL,
  [totsucursal] [int] NULL,
  [ColocadoPtmos] [int] NULL,
  [ptmosNuevoColoca] [int] NULL,
  [cartVencidaIni] [money] NULL,
  [cartVencidaFin] [money] NULL,
  [varCapVencido] [money] NULL,
  [PorVencidaCaInicial] [money] NULL,
  [PtmosIniC1a3] [int] NULL,
  [PtmosIniC4a10] [int] NULL,
  [PtmosIniC11+] [int] NULL,
  [PtmosFinC1a3] [int] NULL,
  [PtmosFinC4a10] [int] NULL,
  [PtmosFinC11+] [int] NULL,
  [crePtmsC1a3] [int] NULL,
  [crePtmsC4a10] [int] NULL,
  [crePtmsC11+] [int] NULL,
  [mes0a3B] [int] NULL,
  [mes3a6B] [int] NULL,
  [mes6B] [int] NULL
)
ON [PRIMARY]
GO