CREATE TABLE [dbo].[tCsComiteActaDetalle] (
  [Acta] [varchar](50) NOT NULL,
  [CodSolicitud] [varchar](15) NOT NULL,
  [CodOficina] [varchar](4) NOT NULL,
  [Asesor] [varchar](120) NOT NULL,
  [CodUsuario] [char](15) NOT NULL,
  [CodGrupo] [varchar](15) NULL,
  [GrupoCliente] [varchar](50) NULL,
  [Clientes] [varchar](120) NULL,
  [CodTipoPlaz] [char](1) NOT NULL,
  [Plazo] [int] NULL,
  [CodDestino] [varchar](15) NULL,
  [TasaInteres] [money] NULL,
  [TipoGarantia] [varchar](5) NOT NULL,
  [NemGarantia] [varchar](200) NULL,
  [DescGarantia] [varchar](200) NULL,
  [NombreProdCorto] [varchar](50) NULL,
  [CodEstado] [varchar](10) NULL,
  [CodEstadoAnte] [varchar](10) NULL,
  [MontoSolicitado] [money] NULL,
  [MontoAprobado] [money] NULL,
  [Destino] [varchar](81) NULL,
  [LabActividad] [varchar](50) NULL,
  [MTS] [money] NULL,
  [MTA] [money] NULL,
  [Observacion] [varchar](2000) NULL,
  [PCodTipoPlan] [int] NULL,
  [CodTipoPlan] [int] NULL,
  [PTipoPlaz] [char](1) NULL,
  [PPlazo] [int] NULL,
  [PCuotas] [int] NULL,
  [Cuotas] [int] NULL,
  [FechaDesembolso] [smalldatetime] NULL,
  [FechaAprobacion] [smalldatetime] NULL,
  [CodPrestamoAnterior] [varchar](50) NULL,
  [Codeudor] [varchar](100) NULL,
  [Aval] [varchar](100) NULL,
  [Terminada] [int] NULL,
  CONSTRAINT [PK_tCaComiteActaDetalle] PRIMARY KEY CLUSTERED ([Acta], [CodSolicitud], [CodOficina], [Asesor], [CodUsuario])
)
ON [PRIMARY]
GO