CREATE TABLE [dbo].[TCEPadronCartera451] (
  [Periodo] [varchar](10) NULL,
  [Nrocliente] [varchar](30) NULL,
  [TipoCliente] [varchar](100) NULL,
  [Nombres] [varchar](300) NULL,
  [Paterno] [varchar](300) NULL,
  [Materno] [varchar](300) NULL,
  [ActividadEconómica] [varchar](300) NULL,
  [Nacionalidad] [varchar](300) NULL,
  [Nacimiento] [smalldatetime] NULL,
  [RFC] [varchar](30) NULL,
  [CURP] [varchar](30) NULL,
  [Genero] [varchar](30) NULL,
  [Calle] [varchar](300) NULL,
  [NroExterior] [varchar](300) NULL,
  [Colonia] [varchar](300) NULL,
  [CodigoPostal] [varchar](10) NULL,
  [Localidad] [varchar](300) NULL,
  [Estado] [varchar](300) NULL,
  [Municipio] [varchar](300) NULL,
  [Pais] [varchar](300) NULL,
  [IngresoMensual] [varchar](300) NULL,
  [Otorgamiento] [smalldatetime] NULL,
  [NroContrato] [varchar](100) NULL,
  [MontoLinea] [money] NULL,
  [Contratos] [int] NULL,
  [ValordeVivienda] [money] NULL,
  [NroAvaluo] [varchar](100) NULL,
  [LoanToValue] [varchar](100) NULL,
  [LocalidadDestinoPtmo] [varchar](300) NULL,
  [MunicipioDestinoPtmo] [varchar](300) NULL,
  [EstadoDestinoPtmo] [varchar](300) NULL,
  [ActEconomicaDestinoPtmo] [varchar](300) NULL
)
ON [PRIMARY]
GO