CREATE TABLE [dbo].[_CAOct17CtaOrden] (
  [Fecha] [smalldatetime] NULL,
  [CodPrestamo] [nvarchar](255) NULL,
  [CodUsuario] [nvarchar](255) NULL,
  [CodOficina] [float] NULL,
  [CodDestino] [float] NULL,
  [MontoDesembolso] [float] NULL,
  [SaldoCapital] [float] NULL,
  [SaldoInteres] [float] NULL,
  [SaldoMoratorio] [float] NULL,
  [OtrosCargos] [float] NULL,
  [Impuestos] [float] NULL,
  [CargoMora] [float] NULL,
  [UltimoMovimiento] [smalldatetime] NULL,
  [CapitalAtrasado] [float] NULL,
  [CapitalVencido] [float] NULL,
  [SaldoEnMora] [float] NULL,
  [TipoCalificacion] [nvarchar](255) NULL,
  [InteresVigente] [float] NULL,
  [InteresVencido] [float] NULL,
  [InteresCtaOrden] [float] NULL,
  [InteresDevengado] [float] NULL,
  [MoratorioVigente] [float] NULL,
  [MoratorioVencido] [float] NULL,
  [MoratorioCtaOrden] [float] NULL,
  [MoratorioDevengado] [float] NULL,
  [SecuenciaCliente] [float] NULL,
  [SecuenciaGrupo] [float] NULL,
  [PReservaCapital] [nvarchar](255) NULL,
  [SReservaCapital] [nvarchar](255) NULL,
  [PReservaInteres] [nvarchar](255) NULL,
  [SReservaInteres] [nvarchar](255) NULL,
  [IDA] [nvarchar](255) NULL,
  [IReserva] [nvarchar](255) NULL
)
ON [PRIMARY]
GO