CREATE TABLE [dbo].[tcscirculoviviendainf] (
  [codusuario] [varchar](30) NULL,
  [actividad_económica] [varchar](50) NULL,
  [calle] [varchar](50) NULL,
  [número_exterior] [varchar](50) NULL,
  [colonia] [varchar](50) NULL,
  [Municipio] [varchar](50) NULL,
  [Localidad] [varchar](50) NULL,
  [Estado] [varchar](50) NULL,
  [Código_postal] [varchar](50) NULL,
  [TipoHogar] [varchar](50) NULL,
  [Pais] [varchar](50) NULL,
  [Apellido_paterno] [varchar](50) NULL,
  [Apellido_materno] [varchar](50) NULL,
  [Nombres] [varchar](50) NULL,
  [Fecha_de_nacimiento] [smalldatetime] NULL,
  [RFC] [varchar](50) NULL,
  [Nacionalidad] [varchar](50) NULL,
  [Genero] [varchar](50) NULL,
  [CURP] [varchar](50) NULL,
  [codprestamo] [varchar](50) NULL,
  [tecnologia] [varchar](50) NULL,
  [GarantiaLiquida] [money] NULL,
  [Frecuencia] [varchar](50) NULL,
  [FechaDesembolso] [smalldatetime] NULL,
  [PorcentajeGarantizaAval] [varchar](50) NULL,
  [MontoDesembolso] [money] NULL,
  [FECHA_DE_LA_PRIMERA_AMORTIZACIÓN__NO_CUBIERTA] [smalldatetime] NULL,
  [nrocuotas] [int] NULL,
  [nrodiasatraso] [int] NULL,
  [PlazoCredito] [int] NULL,
  [FechaVencimiento] [smalldatetime] NULL,
  [Monto_de_la_Garantia] [money] NULL,
  [rel_estado_id] [int] NULL,
  [Estado_dim] [varchar](50) NULL,
  [codubi] [varchar](50) NULL,
  [indicador] [varchar](50) NULL,
  [nombre1] [varchar](50) NULL,
  [nombre2] [varchar](50) NULL
)
ON [PRIMARY]
GO