CREATE TABLE [dbo].[tCsMesGarantias] (
  [Fecha] [smalldatetime] NOT NULL,
  [Codigo] [varchar](25) NOT NULL,
  [CodOficina] [varchar](4) NOT NULL,
  [TipoGarantia] [varchar](5) NOT NULL,
  [DocPropiedad] [varchar](25) NOT NULL,
  [NoAvaluo] [varchar](25) NULL,
  [CodSolicitud] [varchar](15) NULL,
  [Correlativo] [tinyint] NULL,
  [Identificador] [varchar](15) NULL,
  [FechRegistro] [datetime] NULL,
  [FechUltAvaluo] [datetime] NULL,
  [MoComercial] [decimal](19, 4) NULL,
  [MoAfectacion] [decimal](19, 4) NULL,
  [MoFluctu] [decimal](19, 4) NULL,
  [MoDepre] [decimal](19, 4) NULL,
  [MoNeto] [decimal](19, 4) NULL,
  [MoAFavor] [decimal](19, 4) NULL,
  [MoOtros] [decimal](19, 4) NULL,
  [MoAnterior] [decimal](19, 4) NULL,
  [MoHipotecario] [decimal](19, 4) NULL,
  [MoLiqui] [decimal](19, 4) NULL,
  [MoImposi] [decimal](19, 4) NULL,
  [PeMonPatrimonio] [decimal](19, 4) NULL,
  [MoCapacidad] [decimal](19, 4) NULL,
  [CodMoneda] [varchar](2) NULL,
  [CodSistema] [char](2) NULL,
  [TipoCambio] [decimal](19, 4) NULL,
  [PIInscripcion] [varchar](16) NULL,
  [PIFecha] [datetime] NULL,
  [Direccion] [varchar](50) NULL,
  [Ubicacion] [varchar](80) NULL,
  [CodLocalidad] [varchar](6) NULL,
  [DPFEntidad] [bit] NULL,
  [DPFCodTipoEnt] [varchar](3) NULL,
  [DPFCodEntidad] [varchar](3) NULL,
  [DPFCodCuenta] [varchar](50) NULL,
  [DPFFraccionCta] [varchar](8) NULL,
  [DPFRenovacion] [tinyint] NULL,
  [DPFFechAper] [datetime] NULL,
  [DPFFechVen] [datetime] NULL,
  [CDNroDoc] [varchar](50) NULL,
  [CDTipoDoc] [smallint] NULL,
  [CodEntiAseg] [varchar](3) NULL,
  [CodPoliza] [varchar](30) NULL,
  [FechSeguro] [datetime] NULL,
  [FechVencPoli] [datetime] NULL,
  [TipoSeguro] [smallint] NULL,
  [Cobertura] [decimal](19, 4) NULL,
  [FechSalida] [datetime] NULL,
  [Obs] [varchar](200) NULL,
  [EstGarantia] [varchar](10) NULL,
  [EstadoGar] [tinyint] NULL,
  [EsReal] [bit] NULL,
  [Activo] [bit] NULL,
  [Caracteristica] [varchar](500) NULL,
  [CodEntiTipoAseg] [varchar](3) NULL,
  [DocPropiedadAnt] [varchar](25) NULL,
  CONSTRAINT [PK_tCsMesGarantias] PRIMARY KEY CLUSTERED ([Fecha], [Codigo], [CodOficina], [TipoGarantia], [DocPropiedad])
)
ON [PRIMARY]
GO