CREATE TABLE [dbo].[tCsHRptBonoComunal] (
  [fecha] [smalldatetime] NOT NULL,
  [codoficina] [varchar](4) NOT NULL,
  [nomoficina] [varchar](250) NULL,
  [region] [varchar](50) NULL,
  [codasesor] [varchar](15) NOT NULL,
  [nomasesor] [varchar](250) NULL,
  [FechaIngreso] [smalldatetime] NULL,
  [Antiguedad] [varchar](25) NULL,
  [NumEmpleado] [varchar](50) NULL,
  [puesto] [varchar](200) NULL,
  [EstadoAsesor] [varchar](6) NOT NULL,
  [duplicado] [int] NULL,
  [ncliactu] [int] NULL,
  [n60actual] [int] NULL,
  [nquitado] [int] NULL,
  [CtesMesAnt] [int] NULL,
  [CtesNvos] [int] NULL,
  [nliquidado] [int] NULL,
  [ClientesTotales] [numeric](16) NULL,
  [CrecimientoCtes] [numeric](16) NULL,
  [nreasignado] [int] NULL,
  [sreasignado] [decimal](16, 2) NULL,
  [sreasignadom0] [decimal](16, 2) NULL,
  [RenovacionxPrestamo] [int] NULL,
  [RenovacionxCliente] [int] NULL,
  [clientesArenovarenmes] [int] NULL,
  [porrenovar] [int] NULL,
  [SaldoMesAnt] [decimal](16, 4) NULL,
  [SaldoMesAct] [decimal](16, 4) NULL,
  [CrecimientoCartera] [decimal](16, 4) NULL,
  [moraactual] [decimal](16, 2) NULL,
  [BonoxCrecimientoCtes] [numeric](16, 2) NOT NULL,
  [BonoxRenovacion] [numeric](27, 2) NULL,
  [BonoxCarteraVigente] [numeric](16, 2) NOT NULL,
  [BonoxCrecimientoCartera] [numeric](16, 2) NOT NULL,
  [TotalxBonos] [numeric](30, 2) NULL,
  [DeduccionxMorosidad] [numeric](16, 2) NOT NULL,
  [TotalBono] [numeric](38, 6) NULL,
  [s60actual] [decimal](16, 4) NULL,
  [factor] [int] NOT NULL,
  [bonofinal] [numeric](38, 6) NULL,
  [ANT1SC] [int] NULL,
  [ANT1SCm0] [int] NULL,
  [ANT2SC] [int] NULL,
  [ANT2SCm0] [int] NULL,
  CONSTRAINT [PK_tCsHRptBonoComunal] PRIMARY KEY CLUSTERED ([fecha], [codoficina], [codasesor])
)
ON [PRIMARY]
GO