CREATE TABLE [dbo].[Reporte] (
  [CodPrestamo] [varchar](25) NOT NULL,
  [Coordinador] [int] NOT NULL,
  [NombreCompleto] [varchar](120) NULL,
  [CodUsuario] [char](15) NOT NULL,
  [FechaAprobacion] [datetime] NOT NULL,
  [FechaDesembolso] [datetime] NOT NULL,
  [MontoDesembolso] [money] NOT NULL,
  [Fondo] [varchar](5) NOT NULL,
  [Estado] [varchar](50) NOT NULL,
  [CodDocIden] [varchar](5) NOT NULL,
  [DI] [varchar](20) NULL,
  [LabActividad] [varchar](50) NULL,
  [UsOcupacion] [varchar](30) NULL,
  [CodUbiGeo] [varchar](6) NOT NULL,
  [CodPais] [varchar](6) NULL,
  [Direccion] [varchar](150) NOT NULL,
  [NumExterno] [varchar](5) NULL,
  [NumInterno] [varchar](5) NULL,
  [Ubicacion] [varchar](150) NULL,
  [CodPostal] [varchar](10) NULL,
  [SecCuota] [smallint] NOT NULL,
  [FechaVencimiento] [datetime] NOT NULL,
  [FechaNacimiento] [datetime] NOT NULL,
  [MontoCuota] [money] NOT NULL,
  [MontoPago] [money] NOT NULL,
  [CodOficina] [varchar](4) NOT NULL,
  [CodConcepto] [varchar](5) NOT NULL,
  [ValorConcepto] [money] NULL,
  [MorParam] [char](2) NULL,
  [MorValor] [money] NULL,
  [ComParam] [char](2) NULL,
  [ComValor] [money] NULL,
  [IMoParam] [char](2) NULL,
  [IMoValor] [money] NULL,
  [Frecuencia] [char](1) NOT NULL,
  [Plazo] [int] NOT NULL,
  [CodTipoPlan] [tinyint] NOT NULL,
  [CodProducto] [char](3) NULL,
  [CodEstadoCivil] [char](1) NULL,
  [Sexo] [bit] NOT NULL,
  [Salud] [varchar](200) NULL,
  [Codeudor] [varchar](120) NULL,
  [TPCliente] [varchar](2) NULL,
  [CalculoINTE] [varchar](2) NULL,
  [cdCodUsuario] [char](15) NULL,
  [cdCodUbiGeo] [varchar](6) NULL,
  [cdDireccion] [varchar](150) NULL,
  [cdNumExterno] [varchar](10) NULL,
  [cdNumInterno] [varchar](10) NULL,
  [cdUbicacion] [varchar](150) NULL,
  [cdCodPostal] [varchar](10) NULL,
  [CodGrupo] [varchar](15) NULL,
  [Grupo] [varchar](100) NULL,
  [SaldoAtrasado] [decimal](18, 4) NULL,
  [SaldoOtros] [decimal](18, 4) NULL,
  [CResponsable] [varchar](150) NULL,
  [CAsesor] [varchar](150) NULL,
  [CCoordinador] [varchar](150) NULL,
  [Peso] [decimal](10, 2) NULL,
  [Estatura] [decimal](10, 2) NULL,
  [Acta] [varchar](50) NULL
)
ON [PRIMARY]
GO