CREATE TABLE [dbo].[tCsFirmaReporte] (
  [Firma] [varchar](100) NOT NULL,
  [CodOficina] [varchar](4) NULL,
  [Denominacion] [varchar](100) NULL,
  [Denominacion1] [varchar](100) NULL,
  [Denominacion2] [varchar](100) NULL,
  [Sujeto] [varchar](4000) NULL,
  [Sujeto2] [varchar](4000) NULL,
  [Direccion] [varchar](500) NULL,
  [DireccionAgencia] [varchar](500) NULL,
  [DGarantia] [varchar](100) NULL,
  [RECA] [varchar](50) NULL,
  [Fecha1] [datetime] NULL,
  [Fecha2] [datetime] NULL,
  [Saldo1] [decimal](18, 5) NULL,
  [Saldo2] [decimal](18, 5) NULL,
  [Saldo3] [decimal](18, 5) NULL,
  [Saldo4] [decimal](18, 5) NULL,
  [Saldo5] [decimal](18, 5) NULL,
  [Saldo6] [decimal](18, 5) NULL,
  [Dato1] [varchar](50) NULL,
  [Dato2] [varchar](50) NULL,
  [Dato3] [varchar](50) NULL,
  [Dato4] [varchar](50) NULL,
  [Dato5] [varchar](50) NULL,
  [Dato6] [varchar](50) NULL,
  [Dato7] [varchar](3000) NULL,
  [Dato8] [varchar](50) NULL,
  [Dato9] [varchar](50) NULL,
  [Dato10] [varchar](50) NULL,
  [Dato11] [varchar](50) NULL
)
ON [PRIMARY]
GO