CREATE TABLE [dbo].[TCETmpCuentav14] (
  [CodPrestamo] [varchar](25) NOT NULL,
  [CodUsuario] [varchar](25) NOT NULL,
  [ClaveUsuario] [varchar](1006) NULL,
  [NombreUsuario] [varchar](50) NULL,
  [Responsabilidad] [varchar](50) NULL,
  [TipoCuenta] [char](1) NOT NULL,
  [TipoContrato] [varchar](2) NULL,
  [UnidadMonetaria] [varchar](2) NULL,
  [ImporteAvaluo] [decimal](38, 4) NULL,
  [NumeroPagos] [smallint] NULL,
  [FrecuenciaPagos] [char](1) NULL,
  [MontoPagar] [int] NULL,
  [Apertura] [varchar](50) NULL,
  [UltimoPago] [int] NULL,
  [Disposicion] [varchar](50) NULL,
  [Cancelacion] [int] NULL,
  [Reporte] [int] NULL,
  [Garantia] [varchar](200) NULL,
  [CreditoMaximo] [int] NULL,
  [SaldoActual] [int] NULL,
  [LimiteCredito] [varchar](10) NOT NULL,
  [SaldoVencido] [int] NULL,
  [PagosVencidos] [smallint] NULL,
  [MOP] [char](10) NULL,
  [HistoricoPagos] [varchar](10) NOT NULL,
  [Observacion] [int] NULL,
  [PagosReportados] [smallint] NULL,
  [MOP02] [int] NULL,
  [MOP03] [int] NULL,
  [MOP04] [int] NULL,
  [MOP05mas] [int] NULL,
  [AOClave] [varchar](10) NOT NULL,
  [AONombre] [varchar](10) NOT NULL,
  [AOCuenta] [varchar](10) NOT NULL,
  [FprimerIncum] [varchar](50) NULL,
  [SaldoInsoluto] [int] NULL,
  [FinSegmento] [varchar](3) NOT NULL,
  [Montoultpago] [int] NULL,
  [PlazoMeses] [decimal](8, 2) NULL,
  [MontoDesembolso] [int] NULL,
  [DiasAtraso] [smallint] NULL
)
ON [PRIMARY]
GO