CREATE TABLE [dbo].[TblrecCuenta] (
  [Representa] [varchar](15) NOT NULL,
  [Fila] [int] IDENTITY,
  [CodPrestamo] [varchar](25) NOT NULL,
  [CodUsuario] [varchar](25) NULL,
  [ClaveUsuario] [varchar](1006) NULL,
  [NombreUsuario] [varchar](50) NULL,
  [Responsabilidad] [varchar](50) NULL,
  [TipoCuenta] [char](1) NOT NULL,
  [TipoContrato] [varchar](2) NULL,
  [UnidadMonetaria] [varchar](2) NULL,
  [ImporteAvaluo] [varchar](18) NULL,
  [NumeroPagos] [smallint] NULL,
  [FrecuenciaPagos] [char](1) NULL,
  [MontoPagar] [varchar](18) NULL,
  [Apertura] [varchar](50) NULL,
  [UltimoPago] [varchar](50) NULL,
  [Disposicion] [varchar](50) NULL,
  [Cancelacion] [varchar](50) NULL,
  [Reporte] [varchar](50) NULL,
  [Garantia] [varchar](200) NULL,
  [CreditoMaximo] [varchar](18) NULL,
  [SaldoActual] [varchar](18) NULL,
  [LimiteCredito] [varchar](10) NOT NULL,
  [SaldoVencido] [varchar](18) NULL,
  [PagosVencidos] [smallint] NULL,
  [MOP] [char](10) NULL,
  [HistoricoPagos] [varchar](10) NOT NULL,
  [Observacion] [varchar](10) NOT NULL,
  [PagosReportados] [smallint] NULL,
  [MOP02] [int] NULL,
  [MOP03] [int] NULL,
  [MOP04] [int] NULL,
  [MOP05mas] [int] NULL,
  [AOClave] [varchar](10) NOT NULL,
  [AONombre] [varchar](10) NOT NULL,
  [AOCuenta] [varchar](10) NOT NULL,
  [FprimerIncum] [varchar](50) NULL,
  [SaldoInsoluto] [varchar](18) NULL,
  [FinSegmento] [varchar](3) NOT NULL,
  [MontoUltimoPago] [int] NULL,
  [FechaIngresoCarteraVencida] [varchar](1) NOT NULL,
  [MontoCorrespondienteIntereses] [int] NOT NULL,
  [FormaPagoMOP] [char](10) NULL,
  [DiasVencimiento] [int] NOT NULL,
  [PlazoMeses] [decimal](8, 2) NULL,
  [MontoCreditoOriginacion] [int] NULL,
  [CorreoElectronicoConsumidor] [varchar](1) NOT NULL
)
ON [PRIMARY]
GO