CREATE TABLE [dbo].[_aaaaa] (
  [CodOriginal] [varchar](15) NOT NULL,
  [CodUsuario] [varchar](15) NOT NULL,
  [CodOrigen] [varchar](15) NULL,
  [CodOficina] [varchar](4) NULL,
  [CodTPersona] [varchar](2) NULL,
  [CodEntidadTipo] [varchar](3) NULL,
  [FechaIngreso] [datetime] NULL,
  [Paterno] [varchar](50) NULL,
  [Materno] [varchar](50) NULL,
  [Nombres] [varchar](80) NULL,
  [ApeEsposo] [varchar](50) NULL,
  [NombreCompleto] [varchar](300) NULL,
  [CodDocIden] [varchar](5) NULL,
  [DI] [varchar](20) NULL,
  [usCURP] [varchar](20) NULL,
  [UsRFC] [varchar](20) NULL,
  [FechaNacimiento] [smalldatetime] NULL,
  [CodEstadoCivil] [char](1) NULL,
  [Sexo] [bit] NULL,
  [CodPais] [varchar](4) NOT NULL,
  [CodUbiGeoDirFamPri] [varchar](6) NULL,
  [DireccionDirFamPri] [varchar](150) NULL,
  [NumExtFam] [varchar](10) NULL,
  [NumIntFam] [varchar](10) NULL,
  [TelefonoDirFamPri] [varchar](20) NULL,
  [CodPostalFam] [varchar](10) NULL,
  [CodUbiGeoDirNegPri] [varchar](6) NULL,
  [DireccionDirNegPri] [varchar](150) NULL,
  [NumExtNeg] [varchar](10) NULL,
  [NumIntNeg] [varchar](10) NULL,
  [TelefonoDirNegPri] [varchar](20) NULL,
  [CodPostalNeg] [varchar](10) NULL,
  [TelefonoMovil] [varchar](50) NULL,
  [UsCodOcupacion] [varchar](6) NULL,
  [LabCodActividad] [varchar](10) NULL,
  [UsEsResidente] [bit] NULL,
  [UsEsAccionista] [bit] NULL,
  [UsEsEmpleado] [bit] NULL,
  [UsRelacionLaboralNos] [char](1) NULL,
  [JurSigla] [varchar](25) NULL,
  [JurIdTipoJuridica] [smallint] NULL,
  [RubroNegocio] [varchar](100) NULL,
  [Actividad] [varchar](50) NULL,
  [GradoInstruccion] [varchar](50) NULL,
  [IngresoMensual] [decimal](18, 4) NULL,
  [CodUsResp] [char](15) NULL,
  [ClienteDe] [varchar](50) NULL,
  [Activo] [bit] NULL,
  [UsNVivenCon] [int] NULL,
  [UsNDependientes] [int] NULL,
  [UsNHijosMay] [int] NULL,
  [UsNHijosMen] [int] NULL,
  [TipoPropiedadDirFam] [varchar](10) NULL,
  [TipoPropiedadDirNeg] [varchar](10) NULL,
  [TiempoResidirDirFam] [int] NULL,
  [TiempoResidirDirNeg] [int] NULL,
  [SituacionLaboral] [varchar](50) NULL,
  [OtrosIngresos] [decimal](18, 4) NULL,
  [CodConyuge] [varchar](15) NULL,
  [UsRFCBD] [varchar](13) NULL,
  [usCURPBD] [varchar](18) NULL,
  [fechacorte] [smalldatetime] NULL
)
ON [PRIMARY]
GO