CREATE TABLE [dbo].[tCsBuroDetalle] (
  [Carga] [int] NOT NULL,
  [Expediente] [varchar](50) NULL,
  [CodPrestamo] [varchar](25) NOT NULL,
  [CtasTarjetaCreditoActual] [int] NULL,
  [CtasTarjetaCreditoUltimo6] [int] NULL,
  [CtasTarjetaCreditoUltimo12] [int] NULL,
  [CtasTarjetaCreditoUltimo24] [int] NULL,
  [CtasMicrofinancierasActual] [int] NULL,
  [CtasMicrofinancierasUltimo6] [int] NULL,
  [CtasMicrofinancierasUltimo12] [int] NULL,
  [CtasMicrofinancierasUltimo24] [int] NULL,
  [CtasPersonalBancarioActual] [int] NULL,
  [CtasPersonalBancarioUltimo6] [int] NULL,
  [CtasPersonalBancarioUltimo12] [int] NULL,
  [CtasPersonalBancarioUltimo24] [int] NULL,
  [CtasAutomotrizActual] [int] NULL,
  [CtasAutomotrizUltimo6] [int] NULL,
  [CtasAutomotrizUltimo12] [int] NULL,
  [CtasAutomotrizUltimo24] [int] NULL,
  [CtasHipetacariasActual] [int] NULL,
  [CtasHipetacariasUltimo6] [int] NULL,
  [CtasHipetacariasUltimo12] [int] NULL,
  [CtasHipetacariasUltimo24] [int] NULL,
  [CtasTiendasDepartamentalActual] [int] NULL,
  [CtasTiendasDepartamentalUltimo6] [int] NULL,
  [CtasTiendasDepartamentalUltimo12] [int] NULL,
  [CtasTiendasDepartamentalUltimo24] [int] NULL,
  [CtasServcMenosComunicacActual] [int] NULL,
  [CtasServcMenosComunicacUltimo6] [int] NULL,
  [CtasServcMenosComunicacUltimo12] [int] NULL,
  [CtasServcMenosComunicacUltimo24] [int] NULL,
  [CtasComunicacionesActual] [int] NULL,
  [CtasComunicacionesUltimo6] [int] NULL,
  [CtasComunicacionesUltimo12] [int] NULL,
  [CtasComunicacionesUltimo24] [int] NULL,
  [LimiteLineaTarjetaCredito] [decimal](19, 4) NULL,
  [SaldoTarjetaCreditoActual] [decimal](19, 4) NULL,
  [SaldoMicrofinancierasActual] [decimal](19, 4) NULL,
  [SaldoPersonalBancarioActual] [decimal](19, 4) NULL,
  [SaldoAutomotrizActual] [decimal](19, 4) NULL,
  [SaldoHipetacariasActual] [decimal](19, 4) NULL,
  [SaldoTiendasDepartamentalActual] [decimal](19, 4) NULL,
  [SaldoServcMenosComunicacActual] [decimal](19, 4) NULL,
  [SaldoComunicacionesActual] [decimal](19, 4) NULL,
  [VencidoTarjetaCreditoActual] [decimal](19, 4) NULL,
  [VencidoMicrofinancierasActual] [decimal](19, 4) NULL,
  [VencidoPersonalBancarioActual] [decimal](19, 4) NULL,
  [VencidoAutomotrizActual] [decimal](19, 4) NULL,
  [VencidoHipetacariasActual] [decimal](19, 4) NULL,
  [VencidoTiendasDepartamentalActual] [decimal](19, 4) NULL,
  [VencidoServcMenosComunicacActual] [decimal](19, 4) NULL,
  [VencidoComunicacionesActual] [decimal](19, 4) NULL,
  [PATarjetaCreditoActual] [int] NULL,
  [PAMicrofinancierasActual] [int] NULL,
  [PAPersonalBancarioActual] [int] NULL,
  [PAAutomotrizActual] [int] NULL,
  [PAHipetacariasActual] [int] NULL,
  [PATiendasDepartamentalActual] [int] NULL,
  [PAServcMenosComunicacActual] [int] NULL,
  [PAComunicacionesActual] [int] NULL,
  [PMTarjetaCreditoHistorico] [int] NULL,
  [PMMicrofinancierasHistorico] [int] NULL,
  [PMPersonalBancarioHistorico] [int] NULL,
  [PMAutomotrizHistorico] [int] NULL,
  [PMHipetacariasHistorico] [int] NULL,
  [PMTiendasDepartamentalHistorico] [int] NULL,
  [PMServcMenosComunicacHistorico] [int] NULL,
  [PMComunicacionesHistorico] [int] NULL,
  [TotalSaldoActual] [decimal](19, 4) NULL,
  [TotalVencidoActual] [decimal](19, 4) NULL,
  [NroCtasPA] [int] NULL,
  [PMHistorico] [int] NULL,
  CONSTRAINT [PK_tCsBuroDetalle] PRIMARY KEY CLUSTERED ([Carga], [CodPrestamo])
)
ON [PRIMARY]
GO