CREATE TABLE [dbo].[tCsEnviosDelgado] (
  [FROM_1] [varchar](9) NOT NULL,
  [FName] [varchar](30) NOT NULL,
  [LName] [varchar](30) NOT NULL,
  [Addr] [varchar](70) NOT NULL,
  [City] [varchar](25) NOT NULL,
  [State] [varchar](3) NOT NULL,
  [Ctry] [varchar](3) NOT NULL,
  [Zip] [varchar](10) NULL,
  [Phone1] [varchar](18) NULL,
  [Phone2] [varchar](18) NULL,
  [Type] [char](1) NOT NULL,
  [Invoice] [varchar](9) NOT NULL,
  [Invoice_Prov] [varchar](9) NOT NULL,
  [Datecr] [char](10) NOT NULL,
  [_Time] [char](8) NOT NULL,
  [_Ctry] [varchar](3) NOT NULL,
  [_Ctry_to] [varchar](3) NOT NULL,
  [Payin] [varchar](3) NOT NULL,
  [Payout] [varchar](3) NOT NULL,
  [Rate_out] [decimal](9) NOT NULL,
  [Netamt] [decimal](9) NOT NULL,
  [Net_cust] [decimal](9) NULL,
  [Notes] [varchar](250) NULL,
  [IDBANK] [varchar](9) NOT NULL,
  [Account] [varchar](20) NULL,
  [CPF] [varchar](20) NULL,
  [Banco] [varchar](3) NULL,
  [Agencia] [varchar](6) NULL,
  [TipoCuenta] [varchar](4) NULL,
  [Status] [char](1) NOT NULL,
  [To_1] [varchar](9) NOT NULL,
  [DFName] [varchar](30) NOT NULL,
  [DLName] [varchar](30) NOT NULL,
  [DAddr] [varchar](70) NULL,
  [DCity] [varchar](25) NOT NULL,
  [DState] [varchar](3) NOT NULL,
  [DCtry] [varchar](3) NOT NULL,
  [DZip] [varchar](10) NULL,
  [DPhone1] [varchar](18) NULL,
  [DPhone2] [varchar](18) NULL,
  [Urgency] [char](1) NOT NULL,
  CONSTRAINT [PK_tCsEnviosDelgado] PRIMARY KEY CLUSTERED ([FROM_1], [Invoice])
)
ON [PRIMARY]
GO