CREATE TABLE [dbo].[tCRDesactualizadas] (
  [Duplicada] [char](2) NULL,
  [Nivel] [char](2) NULL,
  [Empresa] [varchar](9) NULL,
  [EmpresaKOB] [char](2) NULL,
  [CodPrestamo] [varchar](25) NULL,
  [Reportado] [varchar](8) NULL,
  [Expediente] [varchar](15) NULL,
  [RFC] [varchar](20) NULL,
  [Paterno] [varchar](50) NULL,
  [Materno] [varchar](50) NULL,
  [Adicional] [varchar](50) NULL,
  [Nombre1] [varchar](50) NULL,
  [Nombre2] [varchar](50) NULL,
  [Apertura] [varchar](8) NULL,
  [TipoContrato] [varchar](2) NULL,
  [TipoCuenta] [char](1) NULL,
  [LimiteCredito] [varchar](3) NULL,
  [HistoricoPagos] [varchar](50) NULL,
  [IdBuro] [varchar](20) NULL,
  [Observacion] [varchar](15) NULL,
  [MOP] [varchar](4) NULL,
  [SaldoActual] [varchar](15) NULL,
  [SaldoVencido] [varchar](15) NULL,
  [ActualPago] [varchar](15) NULL,
  [Estado] [varchar](50) NULL,
  [Procedimiento] [varchar](50) NULL,
  [CierreFecha] [varchar](8) NULL,
  [CierreSaldo] [varchar](15) NULL,
  [CierreVencido] [varchar](15) NULL,
  [CierrePago] [varchar](15) NULL,
  [CierreMOP] [varchar](4) NULL,
  [CierreObservacion] [varchar](15) NULL
)
ON [PRIMARY]
GO