CREATE TABLE [dbo].[tCCCuentas] (
  [RFC] [varchar](13) NOT NULL,
  [Item] [int] NOT NULL,
  [FechaActualizacion] [smalldatetime] NULL,
  [RegistroImpugnado] [varchar](4) NULL,
  [ClaveOtorgante] [varchar](10) NULL,
  [NombreOtorgante] [varchar](40) NULL,
  [CuentaActual] [varchar](25) NULL,
  [TipoResponsabilidad] [char](1) NULL,
  [TipoCuenta] [char](1) NULL,
  [TipoCredito] [varchar](2) NULL,
  [ClaveUnidadMonetaria] [varchar](2) NULL,
  [ValorActivoValuacion] [int] NULL,
  [NumeroPagos] [int] NULL,
  [FrecuenciaPagos] [char](1) NULL,
  [MontoPagar] [varchar](9) NULL,
  [FechaAperturaCuenta] [smalldatetime] NULL,
  [FechaUltimoPago] [smalldatetime] NULL,
  [FechaUltimaCompra] [smalldatetime] NULL,
  [FechaCierreCuenta] [smalldatetime] NULL,
  [FechaReporte] [smalldatetime] NULL,
  [UltimaFechaSaldoCero] [smalldatetime] NULL,
  [Garantia] [varchar](200) NULL,
  [CreditoMaximo] [int] NULL,
  [SaldoActual] [int] NULL,
  [LimiteCredito] [int] NULL,
  [SaldoVencido] [int] NULL,
  [NumeroPagosVencidos] [int] NULL,
  [PagoActual] [varchar](2) NULL,
  [HistoricoPagos] [varchar](168) NULL,
  [FechaReHistoPagos] [smalldatetime] NULL,
  [FechaAnHistoPagos] [smalldatetime] NULL,
  [ClavePrevencion] [varchar](2) NULL,
  [TotalPagosReportados] [int] NULL,
  [PeorAtraso] [int] NULL,
  [FechaPeorAtraso] [smalldatetime] NULL,
  [SaldoVencidoPeorAtraso] [int] NULL
)
ON [PRIMARY]
GO