CREATE TABLE [dbo].[tCaReporteDiario] (
  [fecha] [smalldatetime] NOT NULL,
  [periodo] [varchar](6) NULL,
  [InteDevengado] [money] NULL,
  [GastoxInteres] [money] NULL,
  [EPRC] [money] NULL,
  [MargenAjustado] [money] NULL,
  [Co_CobradaPagada] [money] NULL,
  [seguros] [money] NULL,
  [pagoTardio] [money] NULL,
  [OtrosIngresos] [money] NULL,
  [co_ctasDigital] [int] NOT NULL,
  [co_bancarias] [int] NOT NULL,
  [GastoEstimado] [money] NULL,
  [NominaCentral] [money] NULL,
  [NominaRed] [money] NULL,
  [Gastos] [money] NULL,
  [Otros] [money] NULL,
  [ResultadoOp] [money] NULL,
  [GastoTotal] [money] NULL,
  [DevengadoRenov] [money] NULL,
  [DevengadoSinre] [money] NULL,
  [intCobradoRenov] [money] NULL,
  [intCobradoSinre] [money] NULL,
  [interesCobrado] [money] NULL,
  [Programado0a7_s] [money] NULL,
  [Programado8a30_s] [money] NULL,
  [Programado31m_s] [money] NULL,
  [CapPagado0a7_s] [money] NULL,
  [CapPagado8a30_s] [money] NULL,
  [CapPagado31m_s] [money] NULL,
  [monto_puntual] [money] NULL,
  [monto_Anticipado] [money] NULL,
  [monto_Atrasado] [money] NULL,
  [monto_pagoParcial] [money] NULL,
  [intProgramado0a7_s] [money] NULL,
  [intProgramado8a30_s] [money] NULL,
  [intProgramado31m_s] [money] NULL,
  [intPagado0a7_s] [money] NULL,
  [intPagado8a30_s] [money] NULL,
  [intPagado31m_s] [money] NULL,
  [saldoDPF_Fin] [money] NULL,
  [saldoDPF_Ini] [money] NULL,
  [saldoVista_Fin] [money] NULL,
  [saldoVista_Ini] [money] NULL,
  [saldoGarantia_Fin] [money] NULL,
  [saldoGarantia_Ini] [money] NULL,
  [Captacion_Fin] [money] NULL,
  [Captacion_Ini] [money] NULL,
  [PlazoFijo_tasaAnual] [money] NULL,
  [Cartera_tasaAnual] [money] NULL
)
ON [PRIMARY]
GO