CREATE TABLE [dbo].[tCsCartera_CA1222] (
  [Fecha] [smalldatetime] NOT NULL,
  [CodPrestamo] [varchar](25) NOT NULL,
  [CodSolicitud] [varchar](15) NULL,
  [CodOficina] [varchar](4) NULL,
  [CodProducto] [smallint] NULL,
  [CodAsesor] [varchar](15) NULL,
  [CodUsuario] [varchar](15) NULL,
  [CodGrupo] [varchar](15) NULL,
  [CodFondo] [tinyint] NULL,
  [CodTipoCredito] [tinyint] NULL,
  [CodDestino] [char](10) NULL,
  [NivelAprobacion] [varchar](50) NULL,
  [BIS] [int] NULL,
  [Estado] [varchar](50) NULL,
  [EstadoAnterior] [varchar](50) NULL,
  [FechaEstado] [smalldatetime] NULL,
  [FechaCastigo] [smalldatetime] NULL,
  [ProximoVencimiento] [smalldatetime] NULL,
  [TipoReprog] [char](5) NULL,
  [NumReprog] [int] NULL,
  [FechaReprog] [smalldatetime] NULL,
  [PrestamoReprog] [varchar](25) NULL,
  [NroDiasCredito] [int] NULL,
  [NroDiasAtraso] [int] NULL,
  [NroDiasAcumulado] [int] NULL,
  [NroDiasMin] [int] NULL,
  [NroDiasMax] [int] NULL,
  [ModalidadPlazo] [char](2) NULL,
  [NroCuotas] [smallint] NULL,
  [CuotaActual] [int] NULL,
  [NroCuotasPagadas] [smallint] NULL,
  [NroCuotasPorPagar] [smallint] NULL,
  [NroDiasPagocuota1] [smallint] NULL,
  [NrodiasEntreCuotas] [smallint] NULL,
  [SecuenciaSolicitud] [int] NULL,
  [FechaSolicitud] [smalldatetime] NULL,
  [FechaAprobacion] [smalldatetime] NULL,
  [FechaDesembolso] [smalldatetime] NULL,
  [FechaVencimiento] [smalldatetime] NULL,
  [MontoDesembolso] [decimal](19, 4) NULL,
  [CodMoneda] [smallint] NULL,
  [TipoCambio] [decimal](18, 7) NULL,
  [SaldoCapital] [decimal](19, 4) NULL,
  [CapitalVigente] [decimal](19, 4) NULL,
  [CapitalVencido] [decimal](19, 4) NULL,
  [CapitalMonetizado] [decimal](19, 4) NULL,
  [SaldoInteresCorriente] [decimal](19, 4) NULL,
  [SaldoINVE] [decimal](19, 4) NULL,
  [SaldoINPE] [decimal](19, 4) NULL,
  [SaldoEnMora] [decimal](19, 4) NULL,
  [CargoMora] [decimal](19, 4) NULL,
  [OtrosCargos] [decimal](19, 4) NULL,
  [Impuestos] [decimal](19, 4) NULL,
  [CodRuta] [varchar](10) NULL,
  [Calificacion] [char](1) NULL,
  [ProvisionCapital] [decimal](19, 4) NULL,
  [ProvisionInteres] [decimal](19, 4) NULL,
  [GarantiaLiquidaMonetizada] [decimal](19, 4) NULL,
  [GarantiaPreferidaMonetizada] [decimal](19, 4) NULL,
  [GarantiaMuyRapidaRealizacion] [decimal](19, 4) NULL,
  [TotalGarantia] [decimal](19, 4) NULL,
  [FechaUltimoMovimiento] [datetime] NULL,
  [TasaIntCorriente] [decimal](18, 7) NULL,
  [TasaINVE] [decimal](18, 7) NULL,
  [TasaINPE] [decimal](18, 7) NULL,
  [CodAnterior] [varchar](27) NULL,
  [TipoCalificacion] [char](1) NULL,
  [ComisionDesembolso] [decimal](19, 4) NULL,
  [SaldoINTEVig] [decimal](19, 4) NULL,
  [SaldoINPEVig] [decimal](19, 4) NULL,
  [SaldoINTESus] [decimal](19, 4) NULL,
  [SaldoINPESus] [decimal](19, 4) NULL,
  [Condonado] [bit] NULL,
  [Cartera] [varchar](50) NULL,
  [EstadoFinmas] [varchar](50) NULL,
  [Judicial] [varchar](50) NULL,
  [Sectorista2] [varchar](15) NULL,
  [Carta] [varchar](50) NULL,
  [CEmision] [datetime] NULL,
  [Cobranza] [varchar](3) NULL,
  CONSTRAINT [PK_tCsCartera_CA1222] PRIMARY KEY CLUSTERED ([Fecha], [CodPrestamo]) WITH (FILLFACTOR = 80)
)
ON [PRIMARY]
GO