CREATE TABLE [dbo].[tCsResumenCartera] (
  [UBI] [varchar](3) NOT NULL,
  [TSA] [varchar](2) NOT NULL,
  [ClaseCartera] [varchar](50) NOT NULL,
  [CN1] [varchar](100) NOT NULL,
  [CN2] [varchar](100) NOT NULL,
  [ID] [varchar](10) NOT NULL,
  [Titulo] [varchar](50) NOT NULL,
  [TipoSaldo] [varchar](500) NOT NULL,
  [Cartera] [varchar](500) NULL,
  [Ubicacion] [varchar](500) NULL,
  [Fecha] [smalldatetime] NOT NULL,
  [Nivel1] [varchar](200) NOT NULL,
  [Nivel2] [varchar](200) NOT NULL,
  [Reporte] [varchar](5) NOT NULL,
  [Dato] [int] NOT NULL,
  [ADesembolso] [decimal](38, 4) NULL,
  [ASaldo] [decimal](38, 4) NULL,
  [AClientes] [int] NULL,
  [APrestamos] [int] NULL,
  [ACampo] [varchar](50) NOT NULL,
  [AGrupo] [varchar](400) NOT NULL,
  [BDesembolso] [decimal](38, 4) NULL,
  [BSaldo] [decimal](38, 4) NULL,
  [BClientes] [int] NULL,
  [BPrestamos] [int] NULL,
  [BCampo] [varchar](50) NOT NULL,
  [BGrupo] [varchar](400) NOT NULL,
  [CDesembolso] [decimal](38, 4) NULL,
  [CSaldo] [decimal](38, 4) NULL,
  [CClientes] [int] NULL,
  [CPrestamos] [int] NULL,
  [CCampo] [varchar](50) NOT NULL,
  [CGrupo] [varchar](400) NOT NULL,
  [DDesembolso] [decimal](38, 4) NULL,
  [DSaldo] [decimal](38, 4) NULL,
  [DClientes] [int] NULL,
  [DPrestamos] [int] NULL,
  [DCampo] [varchar](50) NOT NULL,
  [DGrupo] [varchar](400) NOT NULL,
  [EDesembolso] [decimal](38, 4) NULL,
  [ESaldo] [decimal](38, 4) NULL,
  [EClientes] [int] NULL,
  [EPrestamos] [int] NULL,
  [ECampo] [varchar](50) NOT NULL,
  [EGrupo] [varchar](400) NOT NULL,
  [FDesembolso] [decimal](38, 4) NULL,
  [FSaldo] [decimal](38, 4) NULL,
  [FClientes] [int] NULL,
  [FPrestamos] [int] NULL,
  [FCampo] [varchar](50) NOT NULL,
  [FGrupo] [varchar](400) NOT NULL,
  [GDesembolso] [decimal](38, 4) NULL,
  [GSaldo] [decimal](38, 4) NULL,
  [GClientes] [int] NULL,
  [GPrestamos] [int] NULL,
  [GCampo] [varchar](50) NULL,
  [GGrupo] [varchar](400) NULL,
  CONSTRAINT [PK_tCsResumenCartera] PRIMARY KEY CLUSTERED ([UBI], [TSA], [ID], [Fecha], [Nivel1], [Nivel2], [Reporte], [Dato])
)
ON [PRIMARY]
GO