CREATE TABLE [dbo].[tCoClAsieContDetalle] (
  [CodServicioAsie] [varchar](7) NOT NULL,
  [CodTipoOpera] [varchar](3) NOT NULL,
  [NroAsiento] [smallint] NOT NULL,
  [Item] [smallint] NOT NULL,
  [CodServicio] [varchar](7) NULL,
  [TipoCuenta] [varchar](3) NULL,
  [Glosa] [varchar](200) NULL,
  [DebAcre] [char](1) NULL,
  [DesagxOpera] [bit] NULL,
  [Activo] [bit] NULL,
  [CtaPropia] [bit] NULL,
  [AgrupaOfi] [bit] NULL,
  [CodOficina] [varchar](4) NULL,
  [AgrupaFdo] [bit] NULL,
  [CodFondo] [varchar](2) NULL,
  [UsaLAux1] [bit] NOT NULL,
  [TipLAux1] [tinyint] NULL,
  [AgrupaLAux1] [bit] NOT NULL,
  [CodLAux1] [varchar](50) NULL,
  [UsaLAux2] [bit] NULL,
  [TipLAux2] [tinyint] NULL,
  [AgrupaLAux2] [bit] NULL,
  [CodLAux2] [varchar](50) NULL,
  [UsaLAux3] [bit] NULL,
  [TipLAux3] [tinyint] NULL,
  [AgrupaLAux3] [bit] NULL,
  [CodLAux3] [varchar](50) NULL,
  [QP1] [varchar](200) NOT NULL,
  [QP2] [varchar](200) NOT NULL,
  [QP3] [varchar](200) NOT NULL,
  [QP4] [varchar](200) NOT NULL,
  [QP5] [varchar](200) NOT NULL,
  [QP6] [varchar](200) NOT NULL,
  [QP7] [varchar](200) NOT NULL,
  [QP8] [varchar](200) NOT NULL,
  [QP9] [varchar](200) NOT NULL,
  [QMonto] [varchar](200) NOT NULL,
  [QGlosa] [varchar](200) NOT NULL,
  [QOficina] [varchar](200) NOT NULL,
  [QFondo] [varchar](200) NOT NULL,
  [QLibro1] [varchar](200) NOT NULL,
  [QLibro2] [varchar](200) NOT NULL,
  [QLibro3] [varchar](200) NOT NULL,
  [SeReplica] [char](1) NOT NULL,
  [TratoMonto] [varchar](6) NOT NULL,
  [RelUnoxUno] [char](1) NOT NULL,
  [CodConcepto] [varchar](50) NOT NULL,
  [Entrapagos] [char](1) NOT NULL,
  [RelUnoxUno2] [char](1) NOT NULL,
  [CodEstado] [varchar](50) NOT NULL,
  [ParaMontos] [tinyint] NOT NULL
)
ON [PRIMARY]
GO