CREATE TABLE [dbo].[tCsAAhProxVencimientos] (
  [Fecha] [smalldatetime] NULL,
  [CodOficina] [varchar](4) NULL,
  [sucursal] [varchar](200) NULL,
  [CodProducto] [varchar](3) NULL,
  [Abreviatura] [varchar](200) NULL,
  [CodUsuario] [varchar](25) NULL,
  [NombreCompleto] [varchar](200) NULL,
  [CodCuenta] [varchar](25) NULL,
  [fraccioncta] [varchar](2) NULL,
  [Renovado] [int] NULL,
  [CodMoneda] [varchar](2) NULL,
  [FechaApertura] [smalldatetime] NULL,
  [FechaVencimiento] [smalldatetime] NULL,
  [TasaInteres] [money] NULL,
  [SaldoCuenta] [money] NULL,
  [MontoInteres] [money] NULL,
  [IntAcumulado] [money] NULL,
  [MontoBloqueado] [money] NULL,
  [Plazo] [int] NULL,
  [FechaIngreso] [smalldatetime] NULL,
  [FechaNacimiento] [smalldatetime] NULL,
  [CodEstadoCivil] [char](1) NULL,
  [CodConyuge] [varchar](25) NULL,
  [Sexo] [char](1) NULL,
  [CodUbiGeoDirFamPri] [varchar](10) NULL,
  [DireccionDirFamPri] [varchar](200) NULL,
  [TelefonoDirFamPri] [varchar](15) NULL,
  [idEstadoCta] [varchar](2) NULL,
  [EstadoCTa] [varchar](50) NULL,
  [TipoInteres] [varchar](20) NULL
)
ON [PRIMARY]
GO