CREATE TABLE [dbo].[tRrtFilaColumna_TUDCAACU] (
  [Identificador] [varchar](15) NOT NULL,
  [Padre] [varchar](400) NULL,
  [Hijo] [varchar](400) NULL,
  [Tabla] [varchar](13) NOT NULL,
  [Cartera] [varchar](14) NOT NULL,
  [Ubicacion] [varchar](8) NOT NULL,
  [Fecha] [smalldatetime] NOT NULL,
  [CodOficina] [varchar](4) NOT NULL,
  [CodPrestamo] [varchar](25) NOT NULL,
  [CodProducto] [smallint] NULL,
  [CodUsuario] [varchar](25) NOT NULL,
  [NroDiasAtraso] [int] NULL,
  [Dias] [int] NULL,
  [SaldoCapital] [decimal](19, 4) NOT NULL,
  [InteresVigente] [decimal](19, 4) NULL,
  [InteresVencido] [decimal](19, 4) NULL,
  [InteresCtaOrden] [decimal](19, 4) NULL,
  [MoratorioVigente] [decimal](19, 4) NULL,
  [MoratorioVencido] [decimal](19, 4) NULL,
  [MoratorioCtaOrden] [decimal](19, 4) NULL,
  [OtrosCargos] [decimal](19, 4) NOT NULL,
  [Impuestos] [decimal](19, 4) NULL,
  [CargoMora] [decimal](19, 4) NULL,
  [SReservaInteres] [decimal](19, 4) NULL,
  [SReservaCapital] [decimal](19, 4) NULL,
  [Oficina] [varchar](1031) NULL,
  [CodAsesor] [varchar](15) NULL,
  [Asesor] [varchar](102) NOT NULL,
  [Genero] [varchar](50) NULL,
  [CP1_Estado] [varchar](102) NOT NULL,
  [CP2_Municipio] [varchar](153) NOT NULL,
  [CP3_Colonia] [varchar](154) NOT NULL,
  [ZonaLugar] [varchar](50) NOT NULL,
  [Regional] [varchar](50) NULL,
  [Desembolso] [decimal](16, 4) NULL,
  [Tecnologia] [varchar](50) NULL,
  [TipoCredito] [varchar](50) NULL,
  [ClaseCartera] [varchar](50) NULL,
  [RFC] [varchar](20) NULL,
  [NCliente] [varchar](300) NULL,
  [Estado] [varchar](50) NULL,
  [Producto] [varchar](50) NULL,
  [Fondo] [varchar](15) NULL,
  [FechaDesembolso] [smalldatetime] NULL,
  [NroCuotas] [smallint] NULL,
  [NroCuotasPagadas] [smallint] NULL,
  [ProximoVencimiento] [smalldatetime] NULL,
  [TieneGarantia] [int] NOT NULL,
  [Edad] [int] NULL,
  [Seguimiento] [int] NOT NULL,
  [TasaInt] [decimal](18, 7) NULL,
  [Registro] [varchar](50) NULL,
  [OperacionGarantia] [varchar](13) NULL,
  [R04B0417] [decimal](23, 4) NULL,
  [DevengadoMes] [decimal](38, 4) NULL,
  [PeriodoDesembolso] [nvarchar](83) NULL,
  [SecuenciaCliente] [varchar](1018) NULL,
  [SecuenciaGrupo] [varchar](1018) NULL,
  [Zona] [varchar](3) NULL,
  [TipoReprog] [char](16) NULL,
  [BIS] [varchar](50) NULL,
  [Sector1] [varchar](50) NULL,
  [Sector2] [varchar](50) NULL,
  [ReasignacionCartera] [varchar](18) NULL
)
ON [PRIMARY]
GO