CREATE TABLE [dbo].[tCsCCDesactualizadas] (
  [fecha] [varchar](8) NOT NULL,
  [archivo] [varchar](35) NOT NULL,
  [CTAduplicada] [varchar](5) NULL,
  [Nivel_desactualizada] [varchar](10) NULL,
  [CuentaActual] [varchar](30) NULL,
  [TipoResponsabilidad] [varchar](3) NULL,
  [TipoCuenta] [varchar](3) NULL,
  [TipoContrato] [varchar](5) NULL,
  [FrecuenciaPagos] [varchar](1) NULL,
  [MontoPagar] [money] NULL,
  [FechaAperturaCuenta] [varchar](10) NULL,
  [FechaUltimoPago] [varchar](10) NULL,
  [FechaUltimaCompra] [varchar](10) NULL,
  [FechaCorte] [varchar](10) NULL,
  [CreditoMaximo] [varchar](5) NULL,
  [SaldoActual] [money] NULL,
  [PagoActual] [varchar](10) NULL,
  [ApellidoPaterno] [varchar](255) NULL,
  [ApellidoMaterno] [varchar](255) NULL,
  [ApellidoAdicional] [varchar](255) NULL,
  [Nombres] [varchar](255) NULL,
  [FechaNacimiento] [varchar](10) NULL,
  [cc_fecha_cierre] [smalldatetime] NULL,
  [cc_saldoactualcuenta] [int] NOT NULL,
  [cc_saldovencido] [int] NOT NULL,
  [cc_importepago] [int] NOT NULL,
  [cc_pagoActual] [varchar](5) NULL,
  [cc_claveobservacion] [varchar](10) NULL,
  [FA_Reportado] [varchar](10) NULL,
  [FA_FechaReporteCC] [varchar](10) NULL,
  [FA_Estado] [varchar](20) NULL
)
ON [PRIMARY]
GO