CREATE TABLE [dbo].[tCsAhorrosBak] (
  [Fecha] [datetime] NOT NULL,
  [CodCuenta] [varchar](25) NOT NULL,
  [FraccionCta] [varchar](8) NOT NULL,
  [Renovado] [tinyint] NOT NULL,
  [CodOficina] [varchar](4) NULL,
  [CodProducto] [varchar](3) NULL,
  [CodMoneda] [tinyint] NULL,
  [CodUsuario] [varchar](15) NULL,
  [FormaManejo] [smallint] NULL,
  [FechaApertura] [datetime] NULL,
  [FechaVencimiento] [datetime] NULL,
  [FechaCierre] [datetime] NULL,
  [TasaInteres] [money] NULL,
  [FechaUltMov] [datetime] NULL,
  [TipoCambioFijo] [decimal](18, 7) NULL,
  [SaldoCuenta] [money] NULL,
  [SaldoMonetizado] [money] NULL,
  [MontoInteres] [money] NULL,
  [IntAcumulado] [money] NULL,
  [MontoInteresCapitalizado] [money] NULL,
  [MontoBloqueado] [money] NULL,
  [MontoRetenido] [money] NULL,
  [InteresCalculado] [money] NULL,
  [Plazo] [numeric](10) NULL,
  [Lucro] [bit] NULL,
  [CodAsesor] [varchar](15) NULL,
  [CodOficinaUltTransaccion] [varchar](4) NULL,
  [TipoUltTransaccion] [smallint] NULL,
  [FechaUltCapitalizacion] [datetime] NULL,
  [IdDocRespaldo] [int] NULL,
  [NroSerie] [varchar](25) NULL,
  [idEstadoCta] [char](2) NULL,
  [NomCuenta] [varchar](80) NULL,
  [FondoConfirmar] [money] NULL,
  [Observacion] [varchar](500) NULL,
  [EnGarantia] [bit] NULL,
  [Garantia] [varchar](50) NULL,
  [CuentaPreferencial] [bit] NULL,
  [CuentaReservada] [bit] NULL,
  [CodCuentaAnt] [varchar](25) NULL,
  [AplicaITF] [bit] NULL,
  [PorcCliente] [int] NULL,
  [PorcInst] [int] NULL,
  [idTipoCapi] [smallint] NULL,
  [FechaCambioEstado] [datetime] NULL,
  [FechaInactivacion] [datetime] NULL,
  [NroSolicitud] [varchar](25) NULL,
  [CodTipoInteres] [smallint] NULL,
  [IdTipoRenova] [smallint] NULL,
  [PlazoDiasRenov] [int] NULL,
  [InteresCapitalizable] [bit] NULL,
  [CodPrestamo] [varchar](25) NULL,
  [MontoGarantia] [money] NULL,
  [TipoConta] [varchar](10) NULL,
  [ContaCodigo] [varchar](25) NULL,
  CONSTRAINT [PK_tCsAhorrosBak] PRIMARY KEY CLUSTERED ([Fecha], [CodCuenta], [FraccionCta], [Renovado])
)
ON [PRIMARY]
GO