CREATE TABLE [dbo].[tCsUnisapCA] (
  [Fecha] [smalldatetime] NOT NULL,
  [Año] [int] NULL,
  [Mes] [int] NULL,
  [NombreCompleto] [varchar](300) NULL,
  [CodUsuario] [varchar](25) NOT NULL,
  [CodOficina] [varchar](4) NULL,
  [NomOficina] [varchar](30) NULL,
  [CodProducto] [smallint] NULL,
  [CodPrestamo] [varchar](25) NOT NULL,
  [Tecnologia] [varchar](50) NULL,
  [TipoCredito] [varchar](50) NULL,
  [Condicion] [varchar](15) NOT NULL,
  [FechaDesembolso] [smalldatetime] NULL,
  [MontoDesembolso] [decimal](16, 4) NULL,
  [FechaVencimiento] [smalldatetime] NULL,
  [TasaIntCorriente] [decimal](18, 7) NULL,
  [TasaIntMora] [decimal](18, 7) NULL,
  [NroCuotas] [smallint] NULL,
  [Frecuencia] [varchar](15) NULL,
  [NroDiasAtraso] [int] NULL,
  [CapitalVigente] [decimal](19, 4) NOT NULL,
  [CapitalVencido] [decimal](19, 4) NOT NULL,
  [InteresVigente] [decimal](19, 4) NULL,
  [InteresVencido] [decimal](19, 4) NULL,
  [CtaOrdInteres] [decimal](19, 4) NULL,
  [CtaOrdMoratorio] [decimal](19, 4) NULL,
  [SaldoPromedio] [decimal](38, 6) NULL,
  [DevengadoPromedio] [decimal](38, 6) NULL,
  [DevengadoMes] [decimal](38, 4) NULL,
  [CtasOrdenRecuperado] [money] NOT NULL,
  [ReservaPreventiva] [decimal](20, 4) NULL,
  [ReservaP100Interes] [decimal](19, 4) NULL,
  [FechaUltimaCapital] [smalldatetime] NULL,
  [FechaUltimoInteres] [smalldatetime] NULL,
  [MontoUltimoCapital] [money] NULL,
  [MontoUltimoInteres] [money] NULL,
  [Estado] [varchar](50) NULL,
  [Reestructurado] [varchar](15) NOT NULL,
  [NumReprog] [int] NULL,
  [NroGarantias] [int] NULL,
  [DescGarantia] [varchar](500) NULL,
  [GarantiaLiquida] [decimal](38, 4) NULL,
  [GarantiaPrendaria] [decimal](38, 4) NULL,
  [GarantiaHipotecaria] [decimal](38, 4) NULL,
  [GarantiaOtras] [decimal](38, 4) NULL,
  [Formalizada] [varchar](2) NOT NULL,
  [Redescuento] [varchar](2) NULL,
  [NemFondo] [varchar](15) NULL,
  [EPreventiva] [decimal](20, 4) NULL,
  [CargoMora] [decimal](19, 4) NULL,
  [PagoXMora] [money] NULL,
  [Comision] [decimal](38, 4) NULL,
  [MoratorioVigente] [decimal](19, 4) NULL,
  [MoratorioVencido] [decimal](19, 4) NULL,
  [CodAsesor] [varchar](15) NULL,
  [Asesor] [varchar](300) NULL,
  [CodUbigeo] [varchar](6) NULL,
  [FechaNacimiento] [smalldatetime] NULL,
  [Edad] [int] NULL,
  [usCURP] [varchar](20) NULL,
  [UsRFC] [varchar](20) NULL,
  [EstadoCivil] [varchar](15) NOT NULL,
  [Sexo] [varchar](50) NOT NULL,
  [RubroNegocio] [varchar](100) NULL,
  [Actividad] [varchar](50) NULL,
  [GradoInstruccion] [varchar](50) NULL,
  [EstadoDireccion] [varchar](150) NULL,
  [Municipio] [varchar](150) NULL,
  [Lugar] [varchar](150) NULL,
  [Direccion] [varchar](150) NULL,
  [FechaCastigo] [smalldatetime] NULL,
  [DiasUltimaCancelacion] [int] NULL
)
ON [PRIMARY]
GO