CREATE TABLE [dbo].[tcscarteradet_prov] (
  [Fecha] [smalldatetime] NOT NULL,
  [CodPrestamo] [varchar](25) NOT NULL,
  [CodUsuario] [varchar](25) NOT NULL,
  [CodOficina] [varchar](4) NOT NULL,
  [CodDestino] [varchar](5) NULL,
  [MontoDesembolso] [money] NULL,
  [SaldoCapital] [money] NOT NULL,
  [SaldoInteres] [money] NOT NULL,
  [SaldoMoratorio] [money] NOT NULL,
  [OtrosCargos] [money] NOT NULL,
  [Impuestos] [money] NULL,
  [CargoMora] [money] NULL,
  [UltimoMovimiento] [smalldatetime] NULL,
  [CapitalAtrasado] [money] NOT NULL,
  [CapitalVencido] [money] NOT NULL,
  [SaldoEnMora] [money] NOT NULL,
  [TipoCalificacion] [char](1) NULL,
  [InteresVigente] [money] NULL,
  [InteresVencido] [money] NULL,
  [InteresCtaOrden] [money] NULL,
  [InteresDevengado] [money] NULL,
  [MoratorioVigente] [money] NULL,
  [MoratorioVencido] [money] NULL,
  [MoratorioCtaOrden] [money] NULL,
  [MoratorioDevengado] [money] NULL,
  [SecuenciaCliente] [tinyint] NULL,
  [SecuenciaGrupo] [tinyint] NULL,
  [PReservaCapital] [money] NULL,
  [SReservaCapital] [money] NULL,
  [PReservaInteres] [money] NULL,
  [SReservaInteres] [money] NULL,
  [IDA] [varchar](3) NULL,
  [IReserva] [varchar](10) NULL,
  CONSTRAINT [PK_tcscarteradet_prov] PRIMARY KEY CLUSTERED ([Fecha], [CodPrestamo], [CodUsuario])
)
ON [PRIMARY]
GO