CREATE TABLE [dbo].[tCACubos1] (
  [fecini] [smalldatetime] NULL,
  [fecfin] [smalldatetime] NULL,
  [sucursal] [varchar](50) NULL,
  [region] [varchar](50) NULL,
  [tipoSucursal] [varchar](7) NOT NULL,
  [nroCreditos] [int] NULL,
  [montoDesembolso] [money] NULL,
  [cosecha] [char](6) NULL,
  [segmentoCartera] [varchar](20) NOT NULL,
  [periodicidad] [varchar](10) NOT NULL,
  [Producto] [varchar](15) NOT NULL,
  [rangoCiclo] [varchar](15) NOT NULL,
  [rangoTasaInteres] [varchar](15) NOT NULL,
  [rangoEdadCliente] [varchar](7) NOT NULL,
  [capitalInicial] [money] NULL,
  [capitalFin] [money] NULL,
  [intVigenteFin] [money] NULL,
  [intVencFin] [money] NULL,
  [capitalInicialFA] [money] NULL,
  [capitalFinFA] [money] NULL,
  [interesFinFA] [money] NULL,
  [saldoTotalFA] [money] NULL,
  [capitalFinProgresemos] [money] NULL,
  [capitalFinCubo] [money] NULL,
  [bucketInicio] [varchar](9) NOT NULL,
  [bucketFin] [varchar](9) NOT NULL,
  [estadoInicial] [varchar](14) NOT NULL,
  [estadoFinal] [varchar](14) NOT NULL,
  [rangoMonto] [varchar](10) NOT NULL,
  [tipoCredito] [varchar](12) NOT NULL,
  [cosechaReprog] [varchar](10) NULL
)
ON [PRIMARY]
GO