CREATE TABLE [dbo].[tCsACaPagosPrograPromSemana_vs2] (
  [fechaprogramado] [smalldatetime] NULL,
  [fechaconsulta] [smalldatetime] NULL,
  [region] [varchar](50) NULL,
  [codoficina] [varchar](4) NULL,
  [sucursal] [varchar](50) NULL,
  [Promotor] [varchar](300) NULL,
  [ciclo] [char](5) NULL,
  [Atraso] [varchar](10) NOT NULL,
  [codproducto] [varchar](3) NULL,
  [modalidadplazo] [char](1) NULL,
  [Programado_N] [int] NULL,
  [Programado_S] [money] NULL,
  [Programado_S_Cuota] [money] NULL,
  [Pagado_S] [money] NULL,
  [Condonado] [money] NULL,
  [saldo] [money] NULL,
  [Anticipado] [int] NULL,
  [Puntual] [int] NULL,
  [Atrasado] [int] NULL,
  [Pagado_N] [int] NULL,
  [SinPago_N] [int] NULL,
  [PagoParcial_N] [int] NULL,
  [PagoParcial_N_Ant] [int] NULL,
  [PagoParcial_N_dia] [int] NULL,
  [Anticipado_S] [money] NULL,
  [Puntual_S] [money] NULL,
  [PagoParcial_S] [money] NULL,
  [Atrasado_S] [money] NULL,
  [PorPagado_N] [decimal](38, 18) NULL,
  [PorPagado_S] [money] NULL
)
ON [PRIMARY]
GO