CREATE TABLE [dbo].[tCsReformulacionDet] (
  [Fecha] [smalldatetime] NOT NULL,
  [CodOficina] [varchar](4) NOT NULL,
  [CodPrestamo] [varchar](25) NOT NULL,
  [NumReprog] [smallint] NOT NULL,
  [Calificacion] [char](1) NOT NULL,
  [CodConcepto] [varchar](5) NOT NULL,
  [Deuda] [money] NULL,
  [Capitalizar] [money] NULL,
  [Pagar] [money] NULL,
  [Condonar] [money] NULL,
  [Diferir] [money] NULL,
  [PlazoCredito] [bit] NULL,
  [PlazoMaxPC] [smallint] NULL,
  [NumCuotaPC] [smallint] NULL,
  [PDiferimiento] [bit] NULL,
  [PlazoMaxPD] [smallint] NULL,
  [NumCuotaPD] [smallint] NULL,
  [PorcInicial] [money] NULL,
  [PorcFinal] [money] NULL,
  [DiferimientoT] [bit] NULL,
  [PlazoMaxDT] [smallint] NULL,
  [NumCuotasDT] [smallint] NULL,
  [SecPago] [int] NULL,
  [MontoPagado] [money] NULL,
  [FechaPago] [datetime] NULL,
  [CodCajero] [char](15) NULL,
  [Pagado] [bit] NULL,
  [Anulado] [bit] NULL,
  [OficinaOperacion] [varchar](4) NOT NULL,
  CONSTRAINT [PK_tCsReformulacionDet] PRIMARY KEY CLUSTERED ([Fecha], [CodOficina], [CodPrestamo], [NumReprog], [CodConcepto], [Calificacion])
)
ON [PRIMARY]
GO