CREATE TABLE [dev_cchavezd].[PruebaSeguiLiq0452] (
  [codprestamo] [varchar](25) NOT NULL,
  [periodo] [varchar](10) NULL,
  [Reporte] [varchar](3) NOT NULL,
  [xIDENTIFICADOR DEL CRÉDITO ASIGNADO METODOLOGÍA CNBV] [varchar](50) NULL,
  [NumeroDisposicion] [int] NOT NULL,
  [ClasificacionContable] [varchar](12) NOT NULL,
  [FechaCorte] [varchar](50) NULL,
  [SaldoIndolutoInicialFC] [decimal](16, 2) NULL,
  [MontoDispuestoFC] [varchar](16) NULL,
  [MontoIntOrdinariosFC] [int] NOT NULL,
  [MontoIntMoratoriosFC] [int] NOT NULL,
  [MontoComisionesFC] [int] NOT NULL,
  [MontoIVAFC] [int] NOT NULL,
  [MontoPaExCapFC] [decimal](16, 2) NULL,
  [MontoPaExIntFC] [decimal](16, 2) NULL,
  [MontoPaExComFC] [decimal](16, 2) NULL,
  [MontoCapPagadoFC] [decimal](16, 2) NULL,
  [MontoIntPagadoFC] [decimal](16, 2) NULL,
  [MontoMorPagadoFC] [decimal](16, 2) NULL,
  [MontoComPagadoFC] [decimal](16, 2) NULL,
  [MontoOtrosAccPagadoFC] [decimal](16, 2) NULL,
  [TasaOrdAnualFC] [varchar](16) NULL,
  [TasaMorAnualFC] [varchar](16) NULL,
  [SaldoIndolutoFC] [int] NOT NULL,
  [FechaUltDisposicion] [varchar](50) NULL,
  [PlazoVctoLineaCredOri] [int] NULL,
  [SaldoPrinInicioPeriodo] [decimal](16, 2) NULL,
  [MontoDispuestoLineaCredIniMes] [varchar](16) NULL,
  [CreditoDisponibleLineaCred] [int] NOT NULL,
  [TasaOrdPeriodo] [varchar](16) NULL,
  [TasaMorPeriodo] [varchar](16) NULL,
  [MontoIntOrdPeriodo] [decimal](16, 2) NOT NULL,
  [MontoIntMorPeriodo] [decimal](16, 2) NOT NULL,
  [MontoIntRefinRecaPeriodo] [int] NOT NULL,
  [MontoIntReversoCobrosPeriodo] [int] NOT NULL,
  [SaldoBaseCalcIntPeriodo] [decimal](16, 2) NULL,
  [NumDiasUtilizaCalcIntPeriodo] [int] NOT NULL,
  [ComisionesPeriodo] [int] NOT NULL,
  [MontoCondonaPeriodo] [varchar](16) NULL,
  [MontoQuitaCastigoPeriodo] [varchar](16) NULL,
  [MontoBonoEFPeriodo] [int] NOT NULL,
  [MontoRecDescuentoPeriodo] [int] NOT NULL,
  [MontoAumeDecrPrincipalPeriodo] [int] NOT NULL,
  [MontoCapPagadoPeriodo] [decimal](16, 2) NULL,
  [MontoIntPagadoPeriodo] [decimal](16, 2) NULL,
  [MontoMorPagadoPeriodo] [decimal](16, 2) NULL,
  [MontoComPagadoPeriodo] [decimal](16, 2) NULL,
  [MontoOtrosAccPagadoPeriodo] [decimal](16, 2) NULL,
  [MontoTotalPagadoPeriodo] [decimal](20, 2) NULL,
  [SaldoPrincipalFinalPeriodo] [int] NOT NULL,
  [SaldoInsolutoFinalPeriodo] [int] NOT NULL,
  [SituacionCredito] [int] NOT NULL,
  [TipoRecuperacion] [int] NOT NULL,
  [NumeroDiasMora] [int] NULL,
  [FechaUltPagoCompleto] [varchar](50) NULL,
  [MontoUltPagoCompleto] [decimal](16, 2) NULL,
  [FechaPrimeraAmorNoCubierta] [varchar](50) NOT NULL,
  [TipoGarantia] [int] NOT NULL,
  [NumeroGarantias] [int] NOT NULL,
  [ProgramaCredGobiernoFederal] [int] NOT NULL,
  [MontoGarantia] [decimal](16, 2) NULL,
  [PorcentajeReprGarantiaSaldoInsoluto] [varchar](4) NOT NULL,
  [GradoPrelacionGarantia] [int] NOT NULL,
  [FechaValuacionGarantia] [varchar](50) NULL,
  [NumeroAvales] [int] NOT NULL,
  [PorcentajeGarantizaAval] [varchar](16) NULL,
  [NombreAval] [varchar](200) NOT NULL,
  [RFCaval] [varchar](13) NOT NULL,
  [TipoCarteraCalifica] [int] NOT NULL,
  [CalificaCubierta] [int] NOT NULL,
  [Calificaexpuesta] [int] NOT NULL,
  [ZonaMarginada] [int] NOT NULL,
  [ClavePrevencion] [int] NULL,
  [FuenteFondeo] [int] NOT NULL,
  [PorceEPMontoCubierto] [varchar](4) NOT NULL,
  [MontoCreditoCubierto] [varchar](4) NOT NULL,
  [MontoEPCubierto] [varchar](4) NOT NULL,
  [PorceEPMontoExpuesto] [varchar](4) NOT NULL,
  [MontoCreditoExpuesto] [varchar](4) NOT NULL,
  [MontoEPExpuesto] [varchar](4) NOT NULL,
  [MontoEPTotalesCalifica] [varchar](4) NOT NULL,
  [MontoEPadicionalRO] [varchar](4) NOT NULL,
  [MontoEPadicionalIntDevNoCobradosVencidos(Balance)] [varchar](4) NOT NULL,
  [MontoEPadicionalCNBV] [varchar](4) NOT NULL,
  [MontoEPadicionalTotal] [varchar](4) NOT NULL,
  [MontoEPadicionalIntDevNoCobradosVencidos(CtaOrden)] [varchar](4) NOT NULL,
  [EPTotalesDerivadasCalificaMesInmediatoAnterior] [decimal](16, 2) NOT NULL
)
ON [PRIMARY]
GO