CREATE TABLE [dev_cchavezd].[PruebaBajas0453] (
  [periodo] [varchar](10) NULL,
  [codprestamo] [varchar](25) NOT NULL,
  [REPORTE] [varchar](3) NOT NULL,
  [xIDENTIFICADOR DEL CRÉDITO ASIGNADO METODOLOGÍA CNBV] [varchar](50) NULL,
  [TIPO BAJA CRÉDITO] [int] NOT NULL,
  [SALDO INSOLUTO DEL CRÉDITO AL MOMENTO DE LA BAJA] [varchar](16) NULL,
  [MONTO TOTAL PAGADO EFECTIVAMENTE POR EL ACREDITADO EN EL MOMENTO DE LA BAJA] [varchar](16) NULL,
  [MONTO RECONOCIDO POR CASTIGOS EN EL PERIODO] [money] NULL,
  [MONTO RECONOCIDO POR CONDONACIÓN EN EL PERIODO] [varchar](16) NULL,
  [MONTO RECONOCIDO POR QUITA EN EL PERIODO] [varchar](16) NULL,
  [MONTO RECONOCIDO POR BONIFICACIONES EN EL PERIODO] [int] NOT NULL,
  [MONTO RECONOCIDO POR DESCUENTOS EN EL PERIODO] [int] NOT NULL,
  [MONTO DEL VALOR DEL BIEN RECIBIDO COMO DACIÓN EN PAGO] [int] NOT NULL,
  [MONTO CANCELADO FUERA DE BALANCE] [varchar](16) NULL,
  [ESTIMACIONES PREVENTIVAS DERIVADAS DE LA CALIFICACÓN CANCELADAS EN EL PERIODO] [varchar](16) NULL,
  [ESTIMACIONES PREVENTIVAS ADICIONALES CANCELADAS EN EL PERIODO] [varchar](16) NULL
)
ON [PRIMARY]
GO