CREATE TABLE [dev_cchavezd].[PruebaRegu0841] (
  [codcuenta] [varchar](25) NOT NULL,
  [periodo] [varchar](10) NULL,
  [reporte] [varchar](3) NOT NULL,
  [codusuario] [varchar](8000) NULL,
  [nombres] [varchar](8000) NULL,
  [paterno] [varchar](50) NULL,
  [materno] [varchar](50) NULL,
  [PersonalidadJuridica] [int] NOT NULL,
  [GradoRiesgo] [int] NOT NULL,
  [actividad] [int] NULL,
  [Nacionalidad] [int] NOT NULL,
  [fechanacimiento] [varchar](50) NULL,
  [rfc] [varchar](8000) NULL,
  [CLAVE UNICA DE REGISTRO DE POBLACIÓN (CURP)] [varchar](8000) NULL,
  [genero] [varchar](1) NOT NULL,
  [calle] [varchar](8000) NULL,
  [numexterior] [varchar](5) NULL,
  [Colonia] [varchar](8000) NULL,
  [codpostal] [varchar](15) NULL,
  [Localidad] [varchar](15) NULL,
  [Estado] [int] NULL,
  [Municipio] [int] NULL,
  [PaisDomicilio] [int] NOT NULL,
  [ClaveSucursal] [varchar](8000) NULL,
  [numcuenta] [varchar](8000) NULL,
  [numcontrato] [varchar](8000) NULL,
  [TipoCliente] [int] NOT NULL,
  [ClasificacionContable] [varchar](12) NOT NULL,
  [ClasificacionCertBursatil] [varchar](8) NOT NULL,
  [TipoProducto] [varchar](9) NULL,
  [fechaapertura] [varchar](50) NULL,
  [fechaprimerdeposito] [varchar](50) NULL,
  [montoprimerdepositoOrigen] [money] NULL,
  [montoprimerdepositoPesos] [money] NULL,
  [fechavencimiento] [varchar](50) NULL,
  [plazovencimiento] [numeric](10) NULL,
  [RangoPlazo] [int] NOT NULL,
  [PeriocidadRend] [int] NOT NULL,
  [TipoTasa] [int] NOT NULL,
  [ValorTasaOri] [money] NULL,
  [ValorTasaPeriodo] [money] NULL,
  [TasaIntReferencia] [int] NOT NULL,
  [DiferencialTasaReferencia] [int] NOT NULL,
  [OperacionDiferencial] [int] NOT NULL,
  [FrecuenciaRevisionTasa] [int] NOT NULL,
  [TipoMoneda] [int] NOT NULL,
  [saldocuenta] [money] NULL,
  [Montodepósito] [money] NULL,
  [Montoretiro] [money] NULL,
  [IntDevenoPag] [money] NULL,
  [SaldoFinalPeriodo] [money] NULL,
  [MONTO DE LOS INTERESES DEL MES] [decimal](16, 2) NULL,
  [ComisionesMes] [int] NOT NULL,
  [FechaUltimoMovi] [varchar](50) NULL,
  [MontoUltimoMovi] [money] NULL,
  [SALDO PROMEDIO DEL PERÍODO] [money] NULL,
  [RetiroAntDeposito] [varchar](3) NOT NULL,
  [MntoCubFProteccion] [decimal](16, 2) NULL,
  [PorcCubFProteccion] [decimal](16, 2) NULL,
  [PorcGarantia] [decimal](16, 2) NULL
)
ON [PRIMARY]
GO