CREATE TABLE [dev_cchavezd].[TestCaPromotor] (
  [fecha] [smalldatetime] NULL,
  [Region] [varchar](50) NULL,
  [codoficina] [varchar](3) NULL,
  [nomoficina] [varchar](30) NULL,
  [codasesor] [varchar](15) NULL,
  [NombrePromotor] [varchar](250) NULL,
  [meses] [int] NOT NULL,
  [nivel] [varchar](20) NOT NULL,
  [BonoTotalMes] [money] NOT NULL,
  [BonoPeriodo] [money] NOT NULL,
  [metacolocacion] [money] NOT NULL,
  [montoColocacion] [money] NOT NULL,
  [AlcanceColocacion] [money] NOT NULL,
  [MetaPuntual] [varchar](2) NOT NULL,
  [capProgramado] [money] NOT NULL,
  [capAnticipado] [money] NOT NULL,
  [monto_puntual] [money] NOT NULL,
  [AlcancePuntual] [money] NOT NULL,
  [MetaAcumulada] [varchar](2) NOT NULL,
  [monto_atrasado] [money] NOT NULL,
  [AlcanceAcumulado] [money] NOT NULL,
  [caVgteInicial] [money] NOT NULL,
  [caVencidaInicial] [money] NOT NULL,
  [caVencidaFinal] [int] NOT NULL,
  [AlcancePasoVencida] [money] NOT NULL,
  [MetaPermanencia] [varchar](2) NOT NULL,
  [ptmosRenov] [int] NOT NULL,
  [ptmosLiqui] [int] NOT NULL,
  [AlcanceRenovados] [money] NOT NULL,
  [descripcion] [varchar](17) NOT NULL
)
ON [PRIMARY]
GO